import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.6)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  panel: {
    width: 620,
    maxHeight: '85vh',
    background: '#111118',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 16,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    position: 'relative',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '18px 24px',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    flexShrink: 0,
  },
  headerIcon: {
    fontSize: 18,
    color: '#00f0ff',
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: '#e0e0e8',
    flex: 1,
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: '#555568',
    fontSize: 16,
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: 4,
  },
  tabs: {
    display: 'flex',
    gap: 0,
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    padding: '0 24px',
    flexShrink: 0,
  },
  tab: {
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    color: '#666680',
    fontSize: 12,
    fontWeight: 600,
    padding: '12px 16px',
    cursor: 'pointer',
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
    transition: 'color 0.15s, border-color 0.15s',
  },
  tabActive: {
    color: '#00f0ff',
    borderBottomColor: '#00f0ff',
  },
  saveMsg: {
    padding: '8px 24px',
    fontSize: 12,
    color: '#22c55e',
    background: 'rgba(34,197,94,0.06)',
    borderBottom: '1px solid rgba(34,197,94,0.1)',
    flexShrink: 0,
  },
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px 24px',
    minHeight: 0,
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: '#00f0ff',
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    margin: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  sectionHint: {
    fontSize: 11,
    color: '#555568',
    marginTop: -6,
    marginBottom: 4,
  },
  badge: {
    fontSize: 10,
    color: '#555568',
    background: 'rgba(255,255,255,0.05)',
    padding: '2px 7px',
    borderRadius: 8,
    fontWeight: 500,
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  label: {
    fontSize: 12,
    color: '#999',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  keyHint: {
    fontSize: 11,
    color: '#555568',
    fontFamily: "'Fira Code', 'JetBrains Mono', monospace",
  },
  connectedDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: '#22c55e',
    boxShadow: '0 0 6px rgba(34, 197, 94, 0.4)',
    display: 'inline-block',
  },
  keyRow: {
    display: 'flex',
    gap: 8,
  },
  keyInput: {
    flex: 1,
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 8,
    padding: '8px 12px',
    color: '#e0e0e8',
    fontSize: 13,
    fontFamily: "'Fira Code', 'JetBrains Mono', monospace",
    outline: 'none',
    transition: 'border-color 0.15s',
  },
  saveBtn: {
    background: 'rgba(0, 240, 255, 0.1)',
    border: '1px solid rgba(0, 240, 255, 0.2)',
    borderRadius: 8,
    color: '#00f0ff',
    fontSize: 12,
    fontWeight: 600,
    padding: '8px 16px',
    cursor: 'pointer',
    transition: 'background 0.15s',
    whiteSpace: 'nowrap',
  },
  divider: {
    height: 1,
    background: 'rgba(255,255,255,0.06)',
    margin: '8px 0',
  },
  toggleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    cursor: 'pointer',
    padding: '4px 0',
  },
  toggle: {
    width: 36,
    height: 20,
    borderRadius: 10,
    border: '1px solid',
    position: 'relative',
    transition: 'background 0.2s, border-color 0.2s',
    flexShrink: 0,
  },
  toggleDot: {
    width: 14,
    height: 14,
    borderRadius: '50%',
    position: 'absolute',
    top: 2,
    left: 2,
    transition: 'transform 0.2s, background 0.2s',
  },
  toggleLabel: {
    fontSize: 13,
    color: '#d0d0d8',
  },
  toggleHint: {
    fontSize: 11,
    color: '#555568',
    marginTop: -4,
    paddingLeft: 48,
  },
  shortcutList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  shortcutRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  shortcutKey: {
    background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 4,
    padding: '3px 10px',
    fontSize: 11,
    fontWeight: 600,
    color: '#888898',
    fontFamily: "'Fira Code', 'JetBrains Mono', monospace",
    minWidth: 100,
    textAlign: 'center',
  },
  shortcutDesc: {
    fontSize: 13,
    color: '#999',
  },
  emptyState: {
    fontSize: 13,
    color: '#555568',
    padding: '16px 0',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  entryList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    maxHeight: 300,
    overflowY: 'auto',
  },
  entry: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 10,
    padding: '10px 12px',
    background: 'rgba(255,255,255,0.02)',
    border: '1px solid rgba(255,255,255,0.05)',
    borderRadius: 8,
  },
  entryContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  },
  entryCategory: {
    fontSize: 10,
    fontWeight: 600,
    color: '#00f0ff',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
  },
  entryText: {
    fontSize: 13,
    color: '#d0d0d8',
    lineHeight: 1.4,
  },
  entryMeta: {
    fontSize: 11,
    color: '#555568',
  },
  deleteBtn: {
    background: 'none',
    border: '1px solid rgba(239,68,68,0.2)',
    borderRadius: 4,
    color: '#ef4444',
    fontSize: 11,
    cursor: 'pointer',
    padding: '2px 6px',
    opacity: 0.5,
    flexShrink: 0,
  },
  loading: {
    fontSize: 13,
    color: '#555568',
    padding: 24,
    textAlign: 'center',
  },
  confirmOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(0,0,0,0.5)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 110,
    borderRadius: 16,
  },
  confirmBox: {
    background: '#1a1a24',
    border: '1px solid rgba(239,68,68,0.2)',
    borderRadius: 12,
    padding: '24px 28px',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    maxWidth: 320,
  },
  confirmMsg: {
    fontSize: 14,
    color: '#e0e0e8',
    lineHeight: 1.5,
    textAlign: 'center',
  },
  confirmBtns: {
    display: 'flex',
    gap: 10,
    justifyContent: 'center',
  },
  confirmCancel: {
    background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 8,
    color: '#999',
    fontSize: 12,
    fontWeight: 600,
    padding: '8px 20px',
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  confirmDelete: {
    background: 'rgba(239,68,68,0.15)',
    border: '1px solid rgba(239,68,68,0.3)',
    borderRadius: 8,
    color: '#ef4444',
    fontSize: 12,
    fontWeight: 600,
    padding: '8px 20px',
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  vaultConnected: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    background: 'rgba(0, 240, 255, 0.04)',
    border: '1px solid rgba(0, 240, 255, 0.12)',
    borderRadius: 8,
  },
  vaultDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: '#22c55e',
    flexShrink: 0,
  },
  vaultPathText: {
    fontSize: 12,
    color: '#d0d0d8',
    fontFamily: "'Fira Code', 'JetBrains Mono', monospace",
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  codeBadge: {
    fontSize: 11,
    background: 'rgba(255,255,255,0.06)',
    padding: '1px 5px',
    borderRadius: 3,
    fontFamily: "'Fira Code', 'JetBrains Mono', monospace",
    color: '#888898',
  },
  disconnectBtn: {
    background: 'rgba(239,68,68,0.08)',
    border: '1px solid rgba(239,68,68,0.2)',
    borderRadius: 8,
    color: '#ef4444',
    fontSize: 12,
    fontWeight: 600,
    padding: '6px 14px',
    cursor: 'pointer',
    alignSelf: 'flex-start',
    transition: 'background 0.15s',
  },
};
