"""TTS privacy gate — Friday's spoken replies must not ship raw PII to Gemini.

A reply generated by a LOCAL model may legitimately contain vault content
(that's the point of local routing). The TTS layer is therefore a cloud
egress point of its own:

  * text containing PII → synthesize with the LOCAL engine (full fidelity,
    nothing leaves the machine)
  * local engine unavailable → Gemini may speak only the SCRUBBED text
  * clean text → Gemini path unchanged
"""
from __future__ import annotations

import io

import pytest

import agent_friday.services.voice_engine as ve

pytestmark = pytest.mark.real_provider_paths

PII_TEXT = "Your SSN is 123-45-6789 and the card ends 4111 1111 1111 1111."  # pragma: allowlist secret
CLEAN_TEXT = "The weather tomorrow looks clear with a high of 78."


class _Recorder:
    def __init__(self, result):
        self.texts = []
        self._result = result

    def __call__(self, text, *a, **k):
        self.texts.append(text)
        return self._result


def test_pii_text_routes_to_local_tts(monkeypatch):
    local = _Recorder(io.BytesIO(b"RIFFlocal"))
    gemini = _Recorder(io.BytesIO(b"RIFFgemini"))
    monkeypatch.setattr(ve, "_synthesize_tts_wav_local", local)
    monkeypatch.setattr(ve, "_synthesize_tts_wav_gemini", gemini)

    buf = ve._synthesize_tts_wav(PII_TEXT)

    assert buf.getvalue() == b"RIFFlocal"
    assert local.texts == [PII_TEXT], "local engine must speak the REAL values"
    assert gemini.texts == [], "raw PII must never reach the Gemini TTS path"


def test_pii_text_falls_back_to_scrubbed_gemini(monkeypatch):
    local = _Recorder(None)            # pyttsx3 unavailable
    gemini = _Recorder(io.BytesIO(b"RIFFgemini"))
    monkeypatch.setattr(ve, "_synthesize_tts_wav_local", local)
    monkeypatch.setattr(ve, "_synthesize_tts_wav_gemini", gemini)

    buf = ve._synthesize_tts_wav(PII_TEXT)

    assert buf.getvalue() == b"RIFFgemini"
    assert gemini.texts, "gemini fallback should have been used"
    sent = gemini.texts[0]
    assert "123-45-6789" not in sent  # pragma: allowlist secret
    assert "4111" not in sent


def test_clean_text_uses_gemini_normally(monkeypatch):
    local = _Recorder(io.BytesIO(b"RIFFlocal"))
    gemini = _Recorder(io.BytesIO(b"RIFFgemini"))
    monkeypatch.setattr(ve, "_synthesize_tts_wav_local", local)
    monkeypatch.setattr(ve, "_synthesize_tts_wav_gemini", gemini)
    # Force the online/Gemini-preferred branch regardless of host env.
    monkeypatch.setattr(ve, "_network_is_offline", lambda: False, raising=False)
    monkeypatch.setattr(ve.core, "GEMINI_API_KEY", "test-key", raising=False)

    buf = ve._synthesize_tts_wav(CLEAN_TEXT)

    assert buf.getvalue() == b"RIFFgemini"
    assert gemini.texts == [CLEAN_TEXT]
    assert local.texts == []
