"""One seam in front of every judgment Friday makes, and a record of each one.

WHY THIS EXISTS, and it is not "to add a model".

On 2026-09-22 we went looking for the training data behind Friday's most
consequential classifier - the one that decides whether an action needs
Stephen's sign-off, which since 2026-09-20 includes sending mail as him. The
answer was `~/.friday/approvals.json`, and it holds ONE record. Friday has
been making gate decisions by substring scan for months and keeping no record
of them, so nobody - not him, not the loop, not a reviewer - can say how often
it is right. That is the actual defect. A better classifier is a later
question and cannot even be evaluated until this one is fixed.

`dissent_gate.classify_severity` is a bare substring scan over a marker list.
Its own docstring documents the failure it could not avoid: "spend" and
"order " are hard markers, and they also appear as ordinary nouns in "Analyze
our spend trends". The fix was a hand-written regex exception for leading
drafting verbs. That is a keyword classifier accumulating patches, and the
patches are invisible in aggregate because nothing counts them.

WHAT THIS MODULE IS

  decide(question, state)  ->  Verdict(answer, confidence, method, ...)

One call site shape, several interchangeable backends, and every call appended
to ~/.friday/decisions.jsonl. That buys three things at once:

  * an audit trail - what was asked, what was answered, and by which method
  * the corpus that does not exist, generated by ordinary use
  * a swap point, so trying a real classifier later is a setting rather than
    surgery on approvals.py

WHAT IT IS NOT

It does not change a single verdict today. `keyword` is the only backend that
ships, it delegates to the existing functions verbatim, and the default stays
`keyword` until something is measured to be better. A module that quietly
altered gate behaviour while claiming to be "just instrumentation" would be
the worst possible version of this.

ON ADDING A MODEL BACKEND LATER

`register_backend()` takes any callable. A Laya-style encoder would go in
there: CPU device (bonsai2 owns most of the GPU), loaded lazily off the boot
path (this codebase already lost six seconds of startup to an eager feature
probe nobody read), temperature refitted on the log this module produces, and
failing open to `keyword` so a missing model degrades instead of blocking.
None of that is built here, deliberately, because the measurement comes first.
"""
from __future__ import annotations

import json
import logging
import os
import threading
import time
from dataclasses import dataclass, field, asdict
from typing import Any, Callable, Dict, Optional

_log = logging.getLogger("friday.decisions")

#: Backend name used when nothing else is configured. Never changes silently:
#: a different default is a settings change with a measurement behind it.
DEFAULT_BACKEND = "keyword"

#: Append-only. One JSON object per line. See `_record`.
LOG_NAME = "decisions.jsonl"

#: Cap on the state text written to the log. The point of the record is to be
#: able to re-score a decision later, which needs the text that was judged -
#: but an 8000-character CSS blob or a whole email body would turn an audit
#: trail into a second copy of the user's data. Long states are truncated and
#: marked, so a reader can never mistake a clipped record for a full one.
MAX_LOGGED_STATE = 2000


@dataclass
class Verdict:
    """What was decided, how sure, and by what.

    `confidence` is Optional on purpose. The keyword backend does not produce
    a probability and must not invent one: a hard-coded 1.0 would read as
    certainty to every consumer and to any future calibration analysis. None
    means "this method does not report confidence", which is a different
    statement from "confident".
    """
    question: str
    answer: Any
    method: str
    confidence: Optional[float] = None
    detail: Dict[str, Any] = field(default_factory=dict)
    elapsed_ms: float = 0.0

    def as_dict(self) -> dict:
        return asdict(self)


# ---------------------------------------------------------------------------
#  BACKENDS
# ---------------------------------------------------------------------------
#
# A backend is `fn(question: str, state: str, **kw) -> (answer, confidence,
# detail)`. Confidence may be None. A backend that raises is never fatal -
# `decide` falls back to `keyword` and records that it did, because a gate
# that fails to classify must still classify.

_BACKENDS: Dict[str, Callable[..., Any]] = {}
_LOCK = threading.Lock()


def register_backend(name: str, fn: Callable[..., Any]) -> None:
    """Add or replace a scorer. Idempotent by name."""
    with _LOCK:
        _BACKENDS[str(name)] = fn


def available_backends() -> list:
    with _LOCK:
        return sorted(_BACKENDS)


def _keyword_backend(question: str, state: str, **kw):
    """Today's behaviour, unchanged, delegating to the existing code.

    Deliberately a thin wrapper rather than a reimplementation. Two copies of
    a security-relevant heuristic is how they drift, and `classify_severity`
    is already documented as the single source of truth for this decision.
    """
    if question == "action_severity":
        from agent_friday.services import dissent_gate as dg
        return dg.classify_severity(state), None, {"source": "dissent_gate"}
    if question == "policy_class":
        from agent_friday.services import approvals as _ap
        from agent_friday.services import dissent_gate as dg
        severity = dg.classify_severity(state)
        cls = ("internal" if severity == "soft"
               else _ap._label_hard_class(state))
        return cls, None, {"source": "dissent_gate+label", "severity": severity}
    raise KeyError("keyword backend has no answer for %r" % question)


register_backend("keyword", _keyword_backend)


# ---------------------------------------------------------------------------
#  THE RECORD
# ---------------------------------------------------------------------------

def log_path():
    from agent_friday.core import FRIDAY_DIR
    return FRIDAY_DIR / LOG_NAME


def _record(row: dict) -> None:
    """Append one decision. Never raises, never blocks a verdict.

    Bookkeeping that can break the thing it observes is worse than no
    bookkeeping: this sits in the path of the approval gate, so a full disk or
    a locked file must cost a log line and nothing else.
    """
    try:
        p = log_path()
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")
    except Exception as e:
        _log.warning("could not record a decision: %s", e)


def _clip(state: str) -> tuple:
    s = "" if state is None else str(state)
    if len(s) <= MAX_LOGGED_STATE:
        return s, False
    return s[:MAX_LOGGED_STATE], True


# ---------------------------------------------------------------------------
#  DECIDE
# ---------------------------------------------------------------------------

def active_backend() -> str:
    """Which scorer to use. Env wins over settings so a run can be pinned.

    An unknown name falls back to `keyword` LOUDLY rather than raising: a typo
    in a setting must not be able to take the approval gate offline.
    """
    name = (os.environ.get("FRIDAY_DECISION_BACKEND") or "").strip()
    if not name:
        try:
            from agent_friday.core import _load_settings
            name = str((_load_settings() or {}).get("decision_backend") or "")
        except Exception:
            name = ""
    name = name or DEFAULT_BACKEND
    with _LOCK:
        known = name in _BACKENDS
    if not known:
        _log.warning("decision backend %r is not registered; using %r",
                     name, DEFAULT_BACKEND)
        return DEFAULT_BACKEND
    return name


def decide(question: str, state: str, *, backend: Optional[str] = None,
           context: Optional[dict] = None, **kw) -> Verdict:
    """Answer one typed question about one state, and write it down.

    `question` is a stable key ("action_severity", "policy_class", ...), not a
    prompt - the whole point is that the same question is comparable across
    backends and across months of log.
    """
    name = backend or active_backend()
    started = time.time()
    fell_back = None

    with _LOCK:
        fn = _BACKENDS.get(name)
    try:
        if fn is None:
            raise KeyError("no backend %r" % name)
        answer, confidence, detail = fn(question, state, **kw)
    except Exception as e:
        # FAIL TO THE INCUMBENT, not to an exception. Everything downstream of
        # this is a gate; an unanswerable question is not a reason to let an
        # action through, nor to crash the caller that was trying to check.
        fell_back = "%s: %s" % (type(e).__name__, e)
        _log.warning("decision backend %r failed on %r (%s); using %r",
                     name, question, fell_back, DEFAULT_BACKEND)
        with _LOCK:
            fn = _BACKENDS[DEFAULT_BACKEND]
        answer, confidence, detail = fn(question, state, **kw)
        name = DEFAULT_BACKEND

    elapsed = (time.time() - started) * 1000.0
    clipped, was_clipped = _clip(state)
    _record({
        "at": time.time(),
        "question": question,
        "state": clipped,
        "state_truncated": was_clipped,
        "answer": answer,
        "confidence": confidence,
        "method": name,
        "detail": detail,
        "elapsed_ms": round(elapsed, 2),
        "fell_back_from": fell_back,
        "context": context or {},
    })
    return Verdict(question=question, answer=answer, method=name,
                   confidence=confidence, detail=detail or {},
                   elapsed_ms=round(elapsed, 2))


# ---------------------------------------------------------------------------
#  READING THE RECORD
# ---------------------------------------------------------------------------

def history(question: Optional[str] = None, limit: int = 200) -> list:
    """Recent decisions, newest first. For the settings UI and for scoring."""
    try:
        p = log_path()
        if not p.exists():
            return []
        rows = []
        for line in p.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except Exception:
                continue
            if question and row.get("question") != question:
                continue
            rows.append(row)
        return rows[::-1][:max(1, int(limit or 200))]
    except Exception:
        return []


def summary() -> dict:
    """Counts by question, answer and method - the 'how is the gate behaving'
    view that did not exist before this module.

    Reads the whole file; it is one line per gated decision, which on this
    machine is a handful a day. If that ever stops being true this should grow
    a tail-only mode rather than silently getting slow.
    """
    rows = history(limit=10 ** 9)
    by_q: Dict[str, Dict[str, Any]] = {}
    for r in rows:
        q = str(r.get("question"))
        slot = by_q.setdefault(q, {"n": 0, "answers": {}, "methods": {},
                                   "fallbacks": 0})
        slot["n"] += 1
        a = str(r.get("answer"))
        slot["answers"][a] = slot["answers"].get(a, 0) + 1
        m = str(r.get("method"))
        slot["methods"][m] = slot["methods"].get(m, 0) + 1
        if r.get("fell_back_from"):
            slot["fallbacks"] += 1
    return {"total": len(rows), "by_question": by_q,
            "path": str(log_path()), "backends": available_backends()}
