"""One seam in front of every judgment Friday makes, and a record of each one.

WHY THIS EXISTS, and it is not "to add a model".

Friday's most consequential classifier decides whether an action needs the
owner's sign-off, which includes sending mail as them. Without this module
its only training data is `~/.friday/approvals.json`, which holds almost
nothing: gate decisions made by substring scan leave no record, so nobody -
not the owner, not the loop, not a reviewer - can say how often it is right. That is the actual defect. A better classifier is a later
question and cannot even be evaluated until this one is fixed.

`dissent_gate.classify_severity` is a bare substring scan over a marker list.
Its own docstring documents the failure it could not avoid: "spend" and
"order " are hard markers, and they also appear as ordinary nouns in "Analyze
our spend trends". The fix was a hand-written regex exception for leading
drafting verbs. That is a keyword classifier accumulating patches, and the
patches are invisible in aggregate because nothing counts them.

WHAT THIS MODULE IS

  decide(question, state)  ->  Verdict(answer, confidence, method, ...)

One call site shape, several interchangeable backends, and every call appended
to ~/.friday/decisions.jsonl. That buys three things at once:

  * an audit trail - what was asked, what was answered, and by which method
  * the corpus that does not exist, generated by ordinary use
  * a swap point, so trying a real classifier later is a setting rather than
    surgery on approvals.py

WHAT IT IS NOT

It does not change a single verdict today. `keyword` is the only backend that
ships, it delegates to the existing functions verbatim, and the default stays
`keyword` until something is measured to be better. A module that quietly
altered gate behaviour while claiming to be "just instrumentation" would be
the worst possible version of this.

ON ADDING A MODEL BACKEND LATER

`register_backend()` takes any callable. A Laya-style encoder would go in
there: CPU device (bonsai2 owns most of the GPU), loaded lazily off the boot
path (this codebase already lost six seconds of startup to an eager feature
probe nobody read), temperature refitted on the log this module produces, and
failing open to `keyword` so a missing model degrades instead of blocking.
None of that is built here, deliberately, because the measurement comes first.
"""
from __future__ import annotations

import contextlib
import contextvars
import hashlib
import json
import logging
import os
import re
import threading
import time
from collections import deque
from dataclasses import dataclass, field, asdict
from typing import Any, Callable, Dict, Optional

_log = logging.getLogger("friday.decisions")

#: Backend name used when nothing else is configured. Never changes silently:
#: a different default is a settings change with a measurement behind it.
DEFAULT_BACKEND = "keyword"

#: Append-only. One JSON object per line. See `_record`.
LOG_NAME = "decisions.jsonl"

#: Cap on the state text written to the log. The point of the record is to be
#: able to re-score a decision later, which needs the text that was judged -
#: but an 8000-character CSS blob or a whole email body would turn an audit
#: trail into a second copy of the user's data. Long states are truncated and
#: marked, so a reader can never mistake a clipped record for a full one.
MAX_LOGGED_STATE = 2000

#: Same two patterns dissent_gate._scrub_and_truncate uses on the governance
#: log. Copied rather than imported so this module stays a leaf - importing
#: dissent_gate at RECORD time would put a circular import in the path of the
#: approval gate, and the keyword backend already imports it lazily.
_EMAIL_RE = re.compile(r"\b[\w.+-]+@[\w-]+\.[\w.-]+\b")
_TOKEN_RE = re.compile(r"\b[A-Za-z0-9_\-]{24,}\b")


@dataclass
class Verdict:
    """What was decided, how sure, and by what.

    `confidence` is Optional on purpose. The keyword backend does not produce
    a probability and must not invent one: a hard-coded 1.0 would read as
    certainty to every consumer and to any future calibration analysis. None
    means "this method does not report confidence", which is a different
    statement from "confident".
    """
    question: str
    answer: Any
    method: str
    confidence: Optional[float] = None
    detail: Dict[str, Any] = field(default_factory=dict)
    elapsed_ms: float = 0.0

    def as_dict(self) -> dict:
        return asdict(self)


# ---------------------------------------------------------------------------
#  BACKENDS
# ---------------------------------------------------------------------------
#
# A backend is `fn(question: str, state: str, **kw) -> (answer, confidence,
# detail)`. Confidence may be None. A backend that raises is never fatal -
# `decide` falls back to `keyword` and records that it did, because a gate
# that fails to classify must still classify.

_BACKENDS: Dict[str, Callable[..., Any]] = {}
_LOCK = threading.Lock()


def register_backend(name: str, fn: Callable[..., Any]) -> None:
    """Add or replace a scorer. Idempotent by name."""
    with _LOCK:
        _BACKENDS[str(name)] = fn


def available_backends() -> list:
    with _LOCK:
        return sorted(_BACKENDS)


def _keyword_backend(question: str, state: str, **kw):
    """Today's behaviour, unchanged, delegating to the existing code.

    Deliberately a thin wrapper rather than a reimplementation. Two copies of
    a security-relevant heuristic is how they drift, and `classify_severity`
    is already documented as the single source of truth for this decision.
    """
    if question == "action_severity":
        from agent_friday.services import dissent_gate as dg
        return dg.classify_severity(state), None, {"source": "dissent_gate"}
    if question == "policy_class":
        from agent_friday.services import approvals as _ap
        from agent_friday.services import dissent_gate as dg
        severity = dg.classify_severity(state)
        cls = ("internal" if severity == "soft"
               else _ap._label_hard_class(state))
        return cls, None, {"source": "dissent_gate+label", "severity": severity}
    raise KeyError("keyword backend has no answer for %r" % question)


register_backend("keyword", _keyword_backend)


# ---------------------------------------------------------------------------
#  THE RECORD
# ---------------------------------------------------------------------------

def log_path():
    from agent_friday.core import FRIDAY_DIR
    return FRIDAY_DIR / LOG_NAME


PROBE_LOG_NAME = "decisions-probes.jsonl"


def probe_log_path():
    from agent_friday.core import FRIDAY_DIR
    return FRIDAY_DIR / PROBE_LOG_NAME


# ---------------------------------------------------------------------------
#  WHY A QUESTION WAS ASKED
# ---------------------------------------------------------------------------
#
# Not every decision is an action. The Grants screen asks the gate about every
# connector tool, with empty arguments, to list what a grant could cover; no
# action is attempted. The week-one review found all 125 disagreements came
# from those checks. A caller that is only probing says so, and its rows (and
# their shadows) go to decisions-probes.jsonl, so decisions.jsonl stays real
# traffic: the evidence a promotion decision is made on.
#
# A caller that knows which tool a question is about says so too. The log
# blanks long identifiers for privacy, which also blanks long tool names; a
# tool name is not a secret, and the owner's labels are per tool.

_PURPOSE: contextvars.ContextVar = contextvars.ContextVar("decision_purpose", default=None)
_TOOL: contextvars.ContextVar = contextvars.ContextVar("decision_tool", default=None)


@contextlib.contextmanager
def purpose(name: str):
    """Mark decisions made inside this block, e.g. "probe:grants_screen"."""
    token = _PURPOSE.set(str(name or "") or None)
    try:
        yield
    finally:
        _PURPOSE.reset(token)


@contextlib.contextmanager
def about_tool(name: str):
    """Name the tool the decisions inside this block are about."""
    token = _TOOL.set(str(name or "") or None)
    try:
        yield
    finally:
        _TOOL.reset(token)


def _is_probe(row: dict) -> bool:
    return str(((row or {}).get("context") or {}).get("purpose") or "").startswith("probe")


def _record(row: dict) -> None:
    """Append one decision. Never raises, never blocks a verdict.

    Bookkeeping that can break the thing it observes is worse than no
    bookkeeping: this sits in the path of the approval gate, so a full disk or
    a locked file must cost a log line and nothing else.

    Off the record nothing is written: a row holds the scrubbed state the
    verdict was made on, which is conversation content.
    """
    try:
        from agent_friday.services import off_record
        if off_record.skip("decisions"):
            return
    except Exception:
        pass
    try:
        p = probe_log_path() if _is_probe(row) else log_path()
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")
    except Exception as e:
        _log.warning("could not record a decision: %s", e)


# ---------------------------------------------------------------------------
#  GATE EVENTS - what guards outward actions, and every change to it
# ---------------------------------------------------------------------------
#
# A separate file from the decision log because it holds no conversation
# content: which scanner is selected, when that changed, by which route, and
# why when the caller said. That makes it safe to keep off the record, and a
# gate whose switch-off leaves no trace is one whose history cannot be read.

GATE_EVENTS_NAME = "gate_events.jsonl"
_GATE_KEYS = ("decision_backend", "decision_shadow", "outward_reads")


def gate_events_path():
    from agent_friday.core import FRIDAY_DIR
    return FRIDAY_DIR / GATE_EVENTS_NAME


def _mode_name(pair: dict) -> str:
    try:
        from agent_friday.services import laya_backend
        return laya_backend.current_mode({k: pair.get(k, "") for k in
                                          ("decision_backend", "decision_shadow")})
    except Exception:
        return "custom"


def _change_source() -> tuple:
    """(source, reason) of the settings write in progress."""
    try:
        from flask import has_request_context, request
        if has_request_context():
            reason = (request.headers.get("X-Friday-Change-Reason") or "").strip()
            return "%s %s" % (request.method, request.path), reason[:300] or None
    except Exception:
        pass
    return "python", None


def record_gate_event(event: str, **fields) -> None:
    """Append one gate event. Never raises; kept off the record too."""
    row = {"at": time.time(), "event": event}
    row.update(fields)
    try:
        p = gate_events_path()
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")
    except Exception as e:
        _log.warning("could not record a gate event: %s", e)


def on_settings_change(before: dict, after: dict) -> None:
    """Called by core._save_settings after every write. Records gate changes."""
    try:
        old = {k: str((before or {}).get(k) or "") for k in _GATE_KEYS}
        new = {k: str((after or {}).get(k) or "") for k in _GATE_KEYS}
        # A key the caller's settings never mention is not a change to it.
        for k in ("outward_reads",):
            if k not in (before or {}) and k not in (after or {}):
                old.pop(k)
                new.pop(k)
        if old == new:
            return
        source, reason = _change_source()
        record_gate_event("gate_mode", **{
            "from": old, "to": new,
            "from_mode": _mode_name(old), "to_mode": _mode_name(new),
            "source": source, "reason": reason})
        _log.warning("approval scanner changed %s -> %s (%s%s)",
                     _mode_name(old), _mode_name(new), source,
                     ": " + reason if reason else "")
    except Exception as e:
        _log.warning("could not record an approval scanner change: %s", e)


def _clip(state: str) -> tuple:
    s = "" if state is None else str(state)
    if len(s) <= MAX_LOGGED_STATE:
        return s, False
    return s[:MAX_LOGGED_STATE], True


def _scrub(state: str) -> str:
    """Remove addresses and secrets from a state before it is written down.

    `gmail_send.request_send` builds its action_description as
    "Send mail as you.\\n\\nFrom: …\\nTo: …\\nCc: …\\nSubject: …\\n\\n<body>",
    that string is what `approvals.classify` hands to `decide`, and `_record`
    would write it verbatim. Unscrubbed, the log that exists to make the gate
    auditable would accumulate every recipient and the first ~1,900
    characters of every message the owner sends - in a file whose whole
    purpose is to be read back later, by a reviewer or by a calibration pass.
    The governance log covering the SAME decision is scrubbed too
    (dissent_gate._scrub_and_truncate).

    It is unconditional and lives here rather than in the callers on purpose.
    A redaction rule that each new call site has to remember is not a rule.

    It costs the corpus nothing that matters: severity and policy_class turn
    on the action's framing ("Send mail as you", "delete", "publish"), never
    on which address is in the To line. A future classifier trained on these
    rows should not be learning recipients anyway.
    """
    t = _EMAIL_RE.sub("<email>", state or "")
    return _TOKEN_RE.sub("<token>", t)


def _state_digest(state: str) -> str:
    """Tie a record to its source without storing the payload twice.

    The durable copy of an approval's full text is the approval itself, in
    approvals.json. Re-scoring later can join on this digest instead of the
    log holding its own copy of the body.
    """
    try:
        return hashlib.sha256((state or "").encode("utf-8")).hexdigest()[:16]
    except Exception:
        return ""


# ---------------------------------------------------------------------------
#  DECIDE
# ---------------------------------------------------------------------------

def active_backend() -> str:
    """Which scorer to use. Env wins over settings so a run can be pinned.

    An unknown name falls back to `keyword` LOUDLY rather than raising: a typo
    in a setting must not be able to take the approval gate offline.
    """
    name = (os.environ.get("FRIDAY_DECISION_BACKEND") or "").strip()
    if not name:
        try:
            from agent_friday.core import _load_settings
            name = str((_load_settings() or {}).get("decision_backend") or "")
        except Exception:
            name = ""
    name = name or DEFAULT_BACKEND
    with _LOCK:
        known = name in _BACKENDS
    if not known:
        _log.warning("decision backend %r is not registered; using %r",
                     name, DEFAULT_BACKEND)
        return DEFAULT_BACKEND
    return name


def shadow_backend() -> Optional[str]:
    """Which backend, if any, scores alongside the deciding one.

    A property of the seam rather than of any one scorer. Shadow mode is how a
    candidate earns the default: it answers the same questions on the same
    real traffic, its answers are written down next to the incumbent's, and it
    governs nothing while it does so. Whatever goes in `decision_backend`
    later should have spent time in here first.

    Env wins over settings, same rule as `active_backend`, so a run can be
    pinned without touching ~/.friday/settings.json.
    """
    name = (os.environ.get("FRIDAY_DECISION_SHADOW") or "").strip()
    if not name:
        try:
            from agent_friday.core import _load_settings
            name = str((_load_settings() or {}).get("decision_shadow") or "")
        except Exception:
            name = ""
    return name or None


#: How many skipped shadow questions are kept for catch-up. Bounded: the oldest
#: goes first, and dropping one is itself written down.
_SHADOW_BACKLOG_MAX = 256
#: How often the catch-up worker looks at the backlog, and how many tries one
#: question gets before it is recorded as given up.
_SHADOW_RETRY_S = 20.0
_SHADOW_MAX_TRIES = 30
#: Tests run shadows on the calling thread; the thread is not what they test.
_SHADOW_SYNC_FOR_TESTS = False

_shadow_backlog: "deque" = deque()
_shadow_backlog_lock = threading.Lock()
_shadow_worker: Optional[threading.Thread] = None


def shadow_backlog_size() -> int:
    with _shadow_backlog_lock:
        return len(_shadow_backlog)


def clear_shadow_backlog() -> None:
    with _shadow_backlog_lock:
        _shadow_backlog.clear()


def _shadow_row(name, question, state, *, decided, decided_by, context,
                started, answer=None, confidence=None, detail=None,
                skipped=None, catch_up=False, asked_at=None) -> dict:
    clipped, was_clipped = _clip(_scrub(state))
    row = {
        "at": time.time(),
        "question": question,
        "state": clipped,
        "state_truncated": was_clipped,
        "state_sha256": _state_digest(state),
        "answer": answer,
        "confidence": confidence,
        "method": name,
        "detail": detail or {},
        "elapsed_ms": round((time.time() - started) * 1000.0, 2),
        # THE FIELD THAT MAKES THIS A SHADOW. Neither a reader nor a later
        # scoring pass may mistake one of these rows for a decision that
        # governed anything.
        "shadow": True,
        "decided": decided,
        "decided_by": decided_by,
        "context": dict(context or {}, shadow_of=decided_by),
    }
    if skipped:
        row["skipped"] = skipped
    else:
        row["agreed"] = (answer == decided)
    if catch_up:
        row["catch_up"] = True
        row["lag_s"] = round(time.time() - float(asked_at or time.time()), 2)
    return row


def _off_record_now() -> bool:
    try:
        from agent_friday.services import off_record
        return bool(off_record.skip("decisions"))
    except Exception:
        return False


def _keep_for_catch_up(item: dict) -> None:
    """Hold a skipped question for later. Never off the record."""
    if _off_record_now():
        return
    dropped = None
    with _shadow_backlog_lock:
        _shadow_backlog.append(item)
        while len(_shadow_backlog) > max(1, int(_SHADOW_BACKLOG_MAX)):
            dropped = _shadow_backlog.popleft()
    if dropped is not None:
        _record(_shadow_row(dropped["name"], dropped["question"], dropped["state"],
                            decided=dropped["decided"], decided_by=dropped["decided_by"],
                            context=dropped["context"], started=time.time(),
                            skipped="dropped from a full catch-up backlog",
                            catch_up=True, asked_at=dropped["asked_at"]))
    _ensure_shadow_worker()


def _score_shadow(name, question, state, *, decided, decided_by, context,
                  catch_up=False, asked_at=None) -> bool:
    """One shadow attempt. True when Laya answered and the row is written."""
    with _LOCK:
        fn = _BACKENDS.get(name)
    if fn is None:
        return True
    t0 = time.time()
    try:
        # `background` lets a backend wait for capacity rather than skip:
        # nothing is waiting on a shadow.
        answer, confidence, detail = fn(question, state, background=True)
    except Exception as e:
        why = "%s: %s" % (type(e).__name__, e)
        if not catch_up:
            _record(_shadow_row(name, question, state, decided=decided,
                                decided_by=decided_by, context=context,
                                started=t0, skipped=why[:300]))
        return False
    _record(_shadow_row(name, question, state, decided=decided,
                        decided_by=decided_by, context=context, started=t0,
                        answer=answer, confidence=confidence, detail=detail,
                        catch_up=catch_up, asked_at=asked_at))
    return True


def drain_shadow_backlog() -> int:
    """Score what the backlog holds, oldest first. Returns how many answered."""
    answered = 0
    with _shadow_backlog_lock:
        items = list(_shadow_backlog)
        _shadow_backlog.clear()
    keep = []
    for i, it in enumerate(items):
        ok = _score_shadow(it["name"], it["question"], it["state"],
                           decided=it["decided"], decided_by=it["decided_by"],
                           context=it["context"], catch_up=True,
                           asked_at=it["asked_at"])
        if ok:
            answered += 1
            continue
        it["tries"] = it.get("tries", 0) + 1
        if it["tries"] >= _SHADOW_MAX_TRIES:
            _record(_shadow_row(it["name"], it["question"], it["state"],
                                decided=it["decided"], decided_by=it["decided_by"],
                                context=it["context"], started=time.time(),
                                skipped="gave up after %d catch-up tries" % it["tries"],
                                catch_up=True, asked_at=it["asked_at"]))
            continue
        # The backend is still not answering; the rest will fare no better now.
        keep.append(it)
        keep.extend(items[i + 1:])
        break
    if keep:
        with _shadow_backlog_lock:
            for it in reversed(keep):
                _shadow_backlog.appendleft(it)
    return answered


def _ensure_shadow_worker() -> None:
    global _shadow_worker
    if _SHADOW_SYNC_FOR_TESTS or os.environ.get("FRIDAY_TESTING") == "1":
        return
    with _shadow_backlog_lock:
        if _shadow_worker is not None and _shadow_worker.is_alive():
            return

        def _loop():
            while True:
                time.sleep(_SHADOW_RETRY_S)
                try:
                    drain_shadow_backlog()
                except Exception as e:
                    _log.debug("shadow catch-up pass failed: %s", e)
                if shadow_backlog_size() == 0:
                    return

        _shadow_worker = threading.Thread(target=_loop, name="decision-shadow-catch-up",
                                          daemon=True)
        _shadow_worker.start()


def _run_shadow(name: str, question: str, state: str, *, decided: Any,
                decided_by: str, context: Optional[dict] = None) -> None:
    """Score `state` with `name` and record it BESIDE the real verdict.

    Off the calling thread, and never raising into the gate: the verdict has
    already been returned by the time this runs.

    NEVER SILENT. A shadow that cannot score right now (the model is still
    loading, or its scoring slots are busy) writes a row saying it was skipped
    and why, and the question is kept, bounded, to be scored once the backend
    can answer, in a row marked `catch_up` with how late it was. Shadow rows
    are the evidence that decides whether a candidate is promoted; a missing
    row is missing evidence exactly where the candidate was weakest. The answer
    is about the state, not the moment, so scoring it late loses nothing.
    """
    item = {"name": name, "question": question, "state": state,
            "decided": decided, "decided_by": decided_by,
            "context": dict(context or {}), "asked_at": time.time()}

    def _go():
        try:
            if not _score_shadow(name, question, state, decided=decided,
                                 decided_by=decided_by, context=context):
                _keep_for_catch_up(item)
        except Exception as e:
            _log.debug("shadow backend %r did not score: %s", name, e)

    if _SHADOW_SYNC_FOR_TESTS:
        _go()
        return
    try:
        threading.Thread(target=_go, name="decision-shadow",
                         daemon=True).start()
    except Exception as e:  # thread exhaustion is not a gate failure
        _log.debug("could not start shadow thread: %s", e)


def decide(question: str, state: str, *, backend: Optional[str] = None,
           context: Optional[dict] = None, **kw) -> Verdict:
    """Answer one typed question about one state, and write it down.

    `question` is a stable key ("action_severity", "policy_class", ...), not a
    prompt - the whole point is that the same question is comparable across
    backends and across months of log.
    """
    name = backend or active_backend()
    started = time.time()
    fell_back = None
    if _PURPOSE.get() or _TOOL.get():
        context = dict(context or {})
        if _PURPOSE.get():
            context["purpose"] = _PURPOSE.get()
        if _TOOL.get():
            context["tool"] = _TOOL.get()

    with _LOCK:
        fn = _BACKENDS.get(name)
    try:
        if fn is None:
            raise KeyError("no backend %r" % name)
        answer, confidence, detail = fn(question, state, **kw)
    except Exception as e:
        # FAIL TO THE INCUMBENT, not to an exception. Everything downstream of
        # this is a gate; an unanswerable question is not a reason to let an
        # action through, nor to crash the caller that was trying to check.
        fell_back = "%s: %s" % (type(e).__name__, e)
        _log.warning("decision backend %r failed on %r (%s); using %r",
                     name, question, fell_back, DEFAULT_BACKEND)
        with _LOCK:
            fn = _BACKENDS[DEFAULT_BACKEND]
        answer, confidence, detail = fn(question, state, **kw)
        name = DEFAULT_BACKEND

    elapsed = (time.time() - started) * 1000.0
    # Scrub BEFORE clipping. The other order would let an address that sits
    # just past the 2000-char boundary survive into the record on the day
    # someone raises the cap.
    clipped, was_clipped = _clip(_scrub(state))
    _record({
        "at": time.time(),
        "question": question,
        "state": clipped,
        "state_truncated": was_clipped,
        "state_sha256": _state_digest(state),
        "answer": answer,
        "confidence": confidence,
        "method": name,
        "detail": detail,
        "elapsed_ms": round(elapsed, 2),
        "fell_back_from": fell_back,
        "context": context or {},
    })
    # AFTER the record and BEFORE the return: the shadow observes a verdict
    # that is already final. Scoring the same state with the SAME backend that
    # just decided would only duplicate the row, so that case is skipped.
    try:
        _shadow = shadow_backend()
        if _shadow and _shadow != name:
            _run_shadow(_shadow, question, state, decided=answer,
                        decided_by=name, context=context)
    except Exception as e:
        _log.debug("shadow dispatch skipped: %s", e)

    return Verdict(question=question, answer=answer, method=name,
                   confidence=confidence, detail=detail or {},
                   elapsed_ms=round(elapsed, 2))


# ---------------------------------------------------------------------------
#  READING THE RECORD
# ---------------------------------------------------------------------------

def history(question: Optional[str] = None, limit: int = 200) -> list:
    """Recent decisions, newest first. For the settings UI and for scoring."""
    try:
        p = log_path()
        if not p.exists():
            return []
        rows = []
        for line in p.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except Exception:
                continue
            if question and row.get("question") != question:
                continue
            rows.append(row)
        return rows[::-1][:max(1, int(limit or 200))]
    except Exception:
        return []


def summary() -> dict:
    """Counts by question, answer and method - the 'how is the gate behaving'
    view that did not exist before this module.

    Reads the whole file; it is one line per gated decision, which on this
    machine is a handful a day. If that ever stops being true this should grow
    a tail-only mode rather than silently getting slow.
    """
    rows = history(limit=10 ** 9)
    by_q: Dict[str, Dict[str, Any]] = {}
    for r in rows:
        q = str(r.get("question"))
        slot = by_q.setdefault(q, {"n": 0, "answers": {}, "methods": {},
                                   "fallbacks": 0})
        slot["n"] += 1
        a = str(r.get("answer"))
        slot["answers"][a] = slot["answers"].get(a, 0) + 1
        m = str(r.get("method"))
        slot["methods"][m] = slot["methods"].get(m, 0) + 1
        if r.get("fell_back_from"):
            slot["fallbacks"] += 1
    return {"total": len(rows), "by_question": by_q,
            "path": str(log_path()), "backends": available_backends()}
