"""One seam in front of every judgment Friday makes, and a record of each one.

WHY THIS EXISTS, and it is not "to add a model".

On 2026-09-22 we went looking for the training data behind Friday's most
consequential classifier - the one that decides whether an action needs
Stephen's sign-off, which since 2026-09-20 includes sending mail as him. The
answer was `~/.friday/approvals.json`, and it holds ONE record. Friday has
been making gate decisions by substring scan for months and keeping no record
of them, so nobody - not him, not the loop, not a reviewer - can say how often
it is right. That is the actual defect. A better classifier is a later
question and cannot even be evaluated until this one is fixed.

`dissent_gate.classify_severity` is a bare substring scan over a marker list.
Its own docstring documents the failure it could not avoid: "spend" and
"order " are hard markers, and they also appear as ordinary nouns in "Analyze
our spend trends". The fix was a hand-written regex exception for leading
drafting verbs. That is a keyword classifier accumulating patches, and the
patches are invisible in aggregate because nothing counts them.

WHAT THIS MODULE IS

  decide(question, state)  ->  Verdict(answer, confidence, method, ...)

One call site shape, several interchangeable backends, and every call appended
to ~/.friday/decisions.jsonl. That buys three things at once:

  * an audit trail - what was asked, what was answered, and by which method
  * the corpus that does not exist, generated by ordinary use
  * a swap point, so trying a real classifier later is a setting rather than
    surgery on approvals.py

WHAT IT IS NOT

It does not change a single verdict today. `keyword` is the only backend that
ships, it delegates to the existing functions verbatim, and the default stays
`keyword` until something is measured to be better. A module that quietly
altered gate behaviour while claiming to be "just instrumentation" would be
the worst possible version of this.

ON ADDING A MODEL BACKEND LATER

`register_backend()` takes any callable. A Laya-style encoder would go in
there: CPU device (bonsai2 owns most of the GPU), loaded lazily off the boot
path (this codebase already lost six seconds of startup to an eager feature
probe nobody read), temperature refitted on the log this module produces, and
failing open to `keyword` so a missing model degrades instead of blocking.
None of that is built here, deliberately, because the measurement comes first.
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import threading
import time
from dataclasses import dataclass, field, asdict
from typing import Any, Callable, Dict, Optional

_log = logging.getLogger("friday.decisions")

#: Backend name used when nothing else is configured. Never changes silently:
#: a different default is a settings change with a measurement behind it.
DEFAULT_BACKEND = "keyword"

#: Append-only. One JSON object per line. See `_record`.
LOG_NAME = "decisions.jsonl"

#: Cap on the state text written to the log. The point of the record is to be
#: able to re-score a decision later, which needs the text that was judged -
#: but an 8000-character CSS blob or a whole email body would turn an audit
#: trail into a second copy of the user's data. Long states are truncated and
#: marked, so a reader can never mistake a clipped record for a full one.
MAX_LOGGED_STATE = 2000

#: Same two patterns dissent_gate._scrub_and_truncate uses on the governance
#: log. Copied rather than imported so this module stays a leaf - importing
#: dissent_gate at RECORD time would put a circular import in the path of the
#: approval gate, and the keyword backend already imports it lazily.
_EMAIL_RE = re.compile(r"\b[\w.+-]+@[\w-]+\.[\w.-]+\b")
_TOKEN_RE = re.compile(r"\b[A-Za-z0-9_\-]{24,}\b")


@dataclass
class Verdict:
    """What was decided, how sure, and by what.

    `confidence` is Optional on purpose. The keyword backend does not produce
    a probability and must not invent one: a hard-coded 1.0 would read as
    certainty to every consumer and to any future calibration analysis. None
    means "this method does not report confidence", which is a different
    statement from "confident".
    """
    question: str
    answer: Any
    method: str
    confidence: Optional[float] = None
    detail: Dict[str, Any] = field(default_factory=dict)
    elapsed_ms: float = 0.0

    def as_dict(self) -> dict:
        return asdict(self)


# ---------------------------------------------------------------------------
#  BACKENDS
# ---------------------------------------------------------------------------
#
# A backend is `fn(question: str, state: str, **kw) -> (answer, confidence,
# detail)`. Confidence may be None. A backend that raises is never fatal -
# `decide` falls back to `keyword` and records that it did, because a gate
# that fails to classify must still classify.

_BACKENDS: Dict[str, Callable[..., Any]] = {}
_LOCK = threading.Lock()


def register_backend(name: str, fn: Callable[..., Any]) -> None:
    """Add or replace a scorer. Idempotent by name."""
    with _LOCK:
        _BACKENDS[str(name)] = fn


def available_backends() -> list:
    with _LOCK:
        return sorted(_BACKENDS)


def _keyword_backend(question: str, state: str, **kw):
    """Today's behaviour, unchanged, delegating to the existing code.

    Deliberately a thin wrapper rather than a reimplementation. Two copies of
    a security-relevant heuristic is how they drift, and `classify_severity`
    is already documented as the single source of truth for this decision.
    """
    if question == "action_severity":
        from agent_friday.services import dissent_gate as dg
        return dg.classify_severity(state), None, {"source": "dissent_gate"}
    if question == "policy_class":
        from agent_friday.services import approvals as _ap
        from agent_friday.services import dissent_gate as dg
        severity = dg.classify_severity(state)
        cls = ("internal" if severity == "soft"
               else _ap._label_hard_class(state))
        return cls, None, {"source": "dissent_gate+label", "severity": severity}
    raise KeyError("keyword backend has no answer for %r" % question)


register_backend("keyword", _keyword_backend)


# ---------------------------------------------------------------------------
#  THE RECORD
# ---------------------------------------------------------------------------

def log_path():
    from agent_friday.core import FRIDAY_DIR
    return FRIDAY_DIR / LOG_NAME


def _record(row: dict) -> None:
    """Append one decision. Never raises, never blocks a verdict.

    Bookkeeping that can break the thing it observes is worse than no
    bookkeeping: this sits in the path of the approval gate, so a full disk or
    a locked file must cost a log line and nothing else.
    """
    try:
        p = log_path()
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")
    except Exception as e:
        _log.warning("could not record a decision: %s", e)


def _clip(state: str) -> tuple:
    s = "" if state is None else str(state)
    if len(s) <= MAX_LOGGED_STATE:
        return s, False
    return s[:MAX_LOGGED_STATE], True


def _scrub(state: str) -> str:
    """Remove addresses and secrets from a state before it is written down.

    ADDED 2026-09-22, and it is a fix to something this module shipped three
    days earlier. `gmail_send.request_send` builds its action_description as
    "Send mail as you.\\n\\nFrom: …\\nTo: …\\nCc: …\\nSubject: …\\n\\n<body>",
    that string is what `approvals.classify` hands to `decide`, and `_record`
    wrote it verbatim. So the log that exists to make the gate auditable was
    about to accumulate every recipient and the first ~1,900 characters of
    every message Stephen sends - in a file whose whole purpose is to be read
    back later, by a reviewer or by a calibration pass. The governance log
    covering the SAME decision has scrubbed since it was written
    (dissent_gate._scrub_and_truncate); this one had no such pass.

    It is unconditional and lives here rather than in the callers on purpose.
    A redaction rule that each new call site has to remember is not a rule.

    It costs the corpus nothing that matters: severity and policy_class turn
    on the action's framing ("Send mail as you", "delete", "publish"), never
    on which address is in the To line. A future classifier trained on these
    rows should not be learning recipients anyway.
    """
    t = _EMAIL_RE.sub("<email>", state or "")
    return _TOKEN_RE.sub("<token>", t)


def _state_digest(state: str) -> str:
    """Tie a record to its source without storing the payload twice.

    The durable copy of an approval's full text is the approval itself, in
    approvals.json. Re-scoring later can join on this digest instead of the
    log holding its own copy of the body.
    """
    try:
        return hashlib.sha256((state or "").encode("utf-8")).hexdigest()[:16]
    except Exception:
        return ""


# ---------------------------------------------------------------------------
#  DECIDE
# ---------------------------------------------------------------------------

def active_backend() -> str:
    """Which scorer to use. Env wins over settings so a run can be pinned.

    An unknown name falls back to `keyword` LOUDLY rather than raising: a typo
    in a setting must not be able to take the approval gate offline.
    """
    name = (os.environ.get("FRIDAY_DECISION_BACKEND") or "").strip()
    if not name:
        try:
            from agent_friday.core import _load_settings
            name = str((_load_settings() or {}).get("decision_backend") or "")
        except Exception:
            name = ""
    name = name or DEFAULT_BACKEND
    with _LOCK:
        known = name in _BACKENDS
    if not known:
        _log.warning("decision backend %r is not registered; using %r",
                     name, DEFAULT_BACKEND)
        return DEFAULT_BACKEND
    return name


def shadow_backend() -> Optional[str]:
    """Which backend, if any, scores alongside the deciding one.

    A property of the seam rather than of any one scorer. Shadow mode is how a
    candidate earns the default: it answers the same questions on the same
    real traffic, its answers are written down next to the incumbent's, and it
    governs nothing while it does so. Whatever goes in `decision_backend`
    later should have spent time in here first.

    Env wins over settings, same rule as `active_backend`, so a run can be
    pinned without touching ~/.friday/settings.json.
    """
    name = (os.environ.get("FRIDAY_DECISION_SHADOW") or "").strip()
    if not name:
        try:
            from agent_friday.core import _load_settings
            name = str((_load_settings() or {}).get("decision_shadow") or "")
        except Exception:
            name = ""
    return name or None


def _run_shadow(name: str, question: str, state: str, *, decided: Any,
                decided_by: str, context: Optional[dict] = None) -> None:
    """Score `state` with `name` and record it BESIDE the real verdict.

    Fire-and-forget on a daemon thread. Three properties, all deliberate:

      * It never blocks. The verdict has already been returned to the caller
        by the time this runs; a 400 ms encoder must not be in front of an
        approval card, and a model still loading must not be either.
      * It never raises into the gate. A shadow that failed is indistinguish-
        able, from the caller's side, from one that never ran.
      * It never queues. A backend that is still warming raises, and the row
        is simply not written. Queueing would mean a burst of decisions during
        warm-up all landing at once, scored against a moment that has passed.
    """
    with _LOCK:
        fn = _BACKENDS.get(name)
    if fn is None:
        return

    def _go():
        try:
            t0 = time.time()
            answer, confidence, detail = fn(question, state, **{})
            clipped, was_clipped = _clip(_scrub(state))
            _record({
                "at": time.time(),
                "question": question,
                "state": clipped,
                "state_truncated": was_clipped,
                "state_sha256": _state_digest(state),
                "answer": answer,
                "confidence": confidence,
                "method": name,
                "detail": detail,
                "elapsed_ms": round((time.time() - t0) * 1000.0, 2),
                # THE FIELD THAT MAKES THIS A SHADOW. Neither a reader nor a
                # later scoring pass may mistake one of these rows for a
                # decision that governed anything.
                "shadow": True,
                "decided": decided,
                "decided_by": decided_by,
                "agreed": (answer == decided),
                "context": dict(context or {}, shadow_of=decided_by),
            })
        except Exception as e:
            _log.debug("shadow backend %r did not score (harmless): %s",
                       name, e)

    try:
        threading.Thread(target=_go, name="decision-shadow",
                         daemon=True).start()
    except Exception as e:  # thread exhaustion is not a gate failure
        _log.debug("could not start shadow thread: %s", e)


def decide(question: str, state: str, *, backend: Optional[str] = None,
           context: Optional[dict] = None, **kw) -> Verdict:
    """Answer one typed question about one state, and write it down.

    `question` is a stable key ("action_severity", "policy_class", ...), not a
    prompt - the whole point is that the same question is comparable across
    backends and across months of log.
    """
    name = backend or active_backend()
    started = time.time()
    fell_back = None

    with _LOCK:
        fn = _BACKENDS.get(name)
    try:
        if fn is None:
            raise KeyError("no backend %r" % name)
        answer, confidence, detail = fn(question, state, **kw)
    except Exception as e:
        # FAIL TO THE INCUMBENT, not to an exception. Everything downstream of
        # this is a gate; an unanswerable question is not a reason to let an
        # action through, nor to crash the caller that was trying to check.
        fell_back = "%s: %s" % (type(e).__name__, e)
        _log.warning("decision backend %r failed on %r (%s); using %r",
                     name, question, fell_back, DEFAULT_BACKEND)
        with _LOCK:
            fn = _BACKENDS[DEFAULT_BACKEND]
        answer, confidence, detail = fn(question, state, **kw)
        name = DEFAULT_BACKEND

    elapsed = (time.time() - started) * 1000.0
    # Scrub BEFORE clipping. The other order would let an address that sits
    # just past the 2000-char boundary survive into the record on the day
    # someone raises the cap.
    clipped, was_clipped = _clip(_scrub(state))
    _record({
        "at": time.time(),
        "question": question,
        "state": clipped,
        "state_truncated": was_clipped,
        "state_sha256": _state_digest(state),
        "answer": answer,
        "confidence": confidence,
        "method": name,
        "detail": detail,
        "elapsed_ms": round(elapsed, 2),
        "fell_back_from": fell_back,
        "context": context or {},
    })
    # AFTER the record and BEFORE the return: the shadow observes a verdict
    # that is already final. Scoring the same state with the SAME backend that
    # just decided would only duplicate the row, so that case is skipped.
    try:
        _shadow = shadow_backend()
        if _shadow and _shadow != name:
            _run_shadow(_shadow, question, state, decided=answer,
                        decided_by=name, context=context)
    except Exception as e:
        _log.debug("shadow dispatch skipped: %s", e)

    return Verdict(question=question, answer=answer, method=name,
                   confidence=confidence, detail=detail or {},
                   elapsed_ms=round(elapsed, 2))


# ---------------------------------------------------------------------------
#  READING THE RECORD
# ---------------------------------------------------------------------------

def history(question: Optional[str] = None, limit: int = 200) -> list:
    """Recent decisions, newest first. For the settings UI and for scoring."""
    try:
        p = log_path()
        if not p.exists():
            return []
        rows = []
        for line in p.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except Exception:
                continue
            if question and row.get("question") != question:
                continue
            rows.append(row)
        return rows[::-1][:max(1, int(limit or 200))]
    except Exception:
        return []


def summary() -> dict:
    """Counts by question, answer and method - the 'how is the gate behaving'
    view that did not exist before this module.

    Reads the whole file; it is one line per gated decision, which on this
    machine is a handful a day. If that ever stops being true this should grow
    a tail-only mode rather than silently getting slow.
    """
    rows = history(limit=10 ** 9)
    by_q: Dict[str, Dict[str, Any]] = {}
    for r in rows:
        q = str(r.get("question"))
        slot = by_q.setdefault(q, {"n": 0, "answers": {}, "methods": {},
                                   "fallbacks": 0})
        slot["n"] += 1
        a = str(r.get("answer"))
        slot["answers"][a] = slot["answers"].get(a, 0) + 1
        m = str(r.get("method"))
        slot["methods"][m] = slot["methods"].get(m, 0) + 1
        if r.get("fell_back_from"):
            slot["fallbacks"] += 1
    return {"total": len(rows), "by_question": by_q,
            "path": str(log_path()), "backends": available_backends()}
