/**
 * settings.ts — Persistent settings storage for Agent Friday.
 * Stores to {userData}/friday-settings.json.
 */

import { app } from 'electron';
import fsAsync from 'fs/promises';
import fs from 'fs';
import path from 'path';

/* ── Psychological Profile (generated by Claude Sonnet from onboarding intake) ── */
export interface PsychologicalProfile {
  openness: number;           // 0-1: How freely they share personal info
  trustReadiness: number;     // 0-1: How quickly they trust an AI companion
  emotionalDepth: number;     // 0-1: Depth of emotional engagement
  humorAsArmor: boolean;      // Do they use humor to deflect?
  guardedness: number;        // 0-1: How guarded/defensive they are
  connectionStyle: 'warm' | 'intellectual' | 'playful' | 'reserved';
  needsFromAI: string;        // What they likely need from an AI companion
  approachStrategy: string;   // How the agent should approach this person
  motherRelationshipInsight: string;  // Key insight from the mother question
  rawAnalysis: string;        // Full analysis text from Claude
}

/* ── Feature Setup State (guided post-onboarding walkthrough) ── */
export type FeatureSetupStep =
  | 'obsidian'
  | 'browser'
  | 'calendar'
  | 'email'
  | 'screen-capture'
  | 'world-monitor'
  | 'intelligence'
  | 'research'
  | 'ai-services'
  | 'voice'
  | 'gateway'
  | 'scheduler';

export interface FeatureSetupState {
  currentStep: number;
  steps: { id: FeatureSetupStep; status: 'pending' | 'completed' | 'skipped' }[];
}

/* ── Personality Evolution State (FridayCore visual uniqueness) ── */
export interface PersonalityEvolutionState {
  sessionCount: number;
  primaryHue: number;         // 0-360, derived from dominant trait
  secondaryHue: number;       // complementary hue
  particleSpeed: number;      // 0.5-2.0, maps to energy level
  cubeFragmentation: number;  // 0-1, maps to complexity/chaos
  coreScale: number;          // 0.8-1.5, maps to presence/confidence
  dustDensity: number;        // 0.5-2.0, maps to thoughtfulness
  glowIntensity: number;      // 0.5-2.0, maps to warmth
}

/* ── Trust Graph Configuration ── */
export interface TrustGraphConfig {
  maxPersons: number;            // Default 200
  evidenceRetention: number;     // Days to keep evidence, default 90
  decayRate: number;             // Trust decay per day of no interaction, default 0.001
  reEvalThreshold: number;       // Evidence count that triggers hermeneutic re-eval, default 5
}

/* ── Intake Responses (raw answers from "Her" questions) ── */
export interface IntakeResponses {
  voicePreference: string;    // Male, female, or neither
  socialDescription: string;  // How they describe themselves socially
  motherRelationship: string; // The key question — or empty if deflected
}

export interface AgentConfig {
  agentName: string;
  agentVoice: string;          // 'Kore' | 'Puck' | 'Ember' | 'Breeze' | 'Juniper' | 'Orbiter'
  agentGender: string;         // 'female' | 'male' | 'neutral'
  agentAccent: string;         // e.g. 'British RP', 'American', 'Australian'
  agentBackstory: string;      // Freeform backstory paragraph
  agentTraits: string[];       // e.g. ['witty', 'warm', 'direct', 'playful']
  agentIdentityLine: string;   // What the agent says when asked who they are
  userName: string;            // The user's name
  onboardingComplete: boolean; // Whether full onboarding has been completed
}

export interface FridaySettings extends AgentConfig {
  autoLaunch: boolean;
  autoScreenCapture: boolean;
  obsidianVaultPath: string;
  geminiApiKey: string;
  anthropicApiKey: string;
  elevenLabsApiKey: string;
  firecrawlApiKey: string;
  perplexityApiKey: string;
  openaiApiKey: string;
  openrouterApiKey: string;
  /** Which model provider to prefer for agent tasks: 'anthropic' | 'openrouter' */
  preferredProvider: 'anthropic' | 'openrouter';
  /** OpenRouter model to use for agent tasks (e.g. 'anthropic/claude-sonnet-4') */
  openrouterModel: string;
  agentVoicesEnabled: boolean;
  wakeWordEnabled: boolean;
  notificationWhisperEnabled: boolean;
  notificationAllowedApps: string[];
  clipboardIntelligenceEnabled: boolean;
  googleCalendarEnabled: boolean;
  googleCalendarTokens: string;
  worldMonitorPath: string;
  // Gateway settings
  gatewayEnabled: boolean;
  telegramBotToken: string;
  telegramOwnerId: string;
  discordBotToken: string;
  discordOwnerId: string;
  // Onboarding & profile
  intakeResponses: IntakeResponses | null;
  psychologicalProfile: PsychologicalProfile | null;
  featureSetupComplete: boolean;
  featureSetupState: FeatureSetupState | null;
  personalityEvolution: PersonalityEvolutionState | null;
  // Desktop evolution (3D visualization structure index)
  desktopEvolutionIndex: number;
  desktopEvolutionLastChange: number;  // timestamp of last structure change
  // Trust Graph
  trustGraphConfig: TrustGraphConfig | null;
}

const DEFAULTS: FridaySettings = {
  // Agent identity (configured during onboarding)
  agentName: '',
  agentVoice: 'Kore',
  agentGender: 'female',
  agentAccent: '',
  agentBackstory: '',
  agentTraits: [],
  agentIdentityLine: '',
  userName: '',
  onboardingComplete: false,
  // App settings
  autoLaunch: false,
  autoScreenCapture: true,
  obsidianVaultPath: '',
  geminiApiKey: '',
  anthropicApiKey: '',
  elevenLabsApiKey: '',
  firecrawlApiKey: '',
  perplexityApiKey: '',
  openaiApiKey: '',
  openrouterApiKey: '',
  preferredProvider: 'anthropic',
  openrouterModel: 'anthropic/claude-sonnet-4',
  agentVoicesEnabled: true,
  wakeWordEnabled: true,
  notificationWhisperEnabled: true,
  notificationAllowedApps: ['Slack', 'Teams', 'Outlook', 'Calendar', 'Discord', 'WhatsApp', 'Telegram'],
  clipboardIntelligenceEnabled: true,
  googleCalendarEnabled: false,
  googleCalendarTokens: '',
  worldMonitorPath: '',
  // Gateway defaults
  gatewayEnabled: false,
  telegramBotToken: '',
  telegramOwnerId: '',
  discordBotToken: '',
  discordOwnerId: '',
  // Onboarding & profile defaults
  intakeResponses: null,
  psychologicalProfile: null,
  featureSetupComplete: false,
  featureSetupState: null,
  personalityEvolution: null,
  desktopEvolutionIndex: 0,
  desktopEvolutionLastChange: 0,
  trustGraphConfig: null,
};

class SettingsManager {
  private settings: FridaySettings = { ...DEFAULTS };
  private filePath = '';
  private savePromise: Promise<void> = Promise.resolve(); // Write queue to prevent concurrent file writes

  async initialize(): Promise<void> {
    const userDataDir = app.getPath('userData');

    // Migration: rename eve-settings.json → friday-settings.json
    const oldSettingsPath = path.join(userDataDir, 'eve-settings.json');
    const newSettingsPath = path.join(userDataDir, 'friday-settings.json');
    if (fs.existsSync(oldSettingsPath) && !fs.existsSync(newSettingsPath)) {
      fs.renameSync(oldSettingsPath, newSettingsPath);
    }

    // Migration: rename eve-data → friday-data
    const oldDataDir = path.join(userDataDir, 'eve-data');
    const newDataDir = path.join(userDataDir, 'friday-data');
    if (fs.existsSync(oldDataDir) && !fs.existsSync(newDataDir)) {
      fs.renameSync(oldDataDir, newDataDir);
    }

    // Migration: rename eve-intelligence.md → friday-intelligence.md
    const oldIntelPath = path.join(userDataDir, 'eve-intelligence.md');
    const newIntelPath = path.join(userDataDir, 'friday-intelligence.md');
    if (fs.existsSync(oldIntelPath) && !fs.existsSync(newIntelPath)) {
      fs.renameSync(oldIntelPath, newIntelPath);
    }

    this.filePath = path.join(userDataDir, 'friday-settings.json');

    try {
      const data = await fsAsync.readFile(this.filePath, 'utf-8');
      const saved = JSON.parse(data);
      this.settings = { ...DEFAULTS, ...saved };
    } catch {
      // First run — use defaults
    }

    // Merge in .env values if settings are empty (migration from .env-only setup)
    if (!this.settings.geminiApiKey && process.env.GEMINI_API_KEY) {
      this.settings.geminiApiKey = process.env.GEMINI_API_KEY;
    }
    if (!this.settings.anthropicApiKey && process.env.ANTHROPIC_API_KEY) {
      this.settings.anthropicApiKey = process.env.ANTHROPIC_API_KEY;
    }
    if (!this.settings.elevenLabsApiKey && process.env.ELEVENLABS_API_KEY) {
      this.settings.elevenLabsApiKey = process.env.ELEVENLABS_API_KEY;
    }
    if (!this.settings.firecrawlApiKey && process.env.FIRECRAWL_API_KEY) {
      this.settings.firecrawlApiKey = process.env.FIRECRAWL_API_KEY;
    }
    if (!this.settings.perplexityApiKey && process.env.PERPLEXITY_API_KEY) {
      this.settings.perplexityApiKey = process.env.PERPLEXITY_API_KEY;
    }
    if (!this.settings.openaiApiKey && process.env.OPENAI_API_KEY) {
      this.settings.openaiApiKey = process.env.OPENAI_API_KEY;
    }
    if (!this.settings.openrouterApiKey && process.env.OPENROUTER_API_KEY) {
      this.settings.openrouterApiKey = process.env.OPENROUTER_API_KEY;
    }

    // Apply API keys to process.env so the rest of the app can use them
    this.applyApiKeys();

    console.log('[Settings] Initialized (autoLaunch:', this.settings.autoLaunch + ')');
  }

  get(): FridaySettings {
    return { ...this.settings };
  }

  /** Get settings with API keys masked for display */
  getMasked(): Record<string, unknown> {
    return {
      autoLaunch: this.settings.autoLaunch,
      autoScreenCapture: this.settings.autoScreenCapture,
      obsidianVaultPath: this.settings.obsidianVaultPath,
      hasGeminiKey: !!this.settings.geminiApiKey,
      hasAnthropicKey: !!this.settings.anthropicApiKey,
      hasElevenLabsKey: !!this.settings.elevenLabsApiKey,
      hasFirecrawlKey: !!this.settings.firecrawlApiKey,
      hasPerplexityKey: !!this.settings.perplexityApiKey,
      hasOpenaiKey: !!this.settings.openaiApiKey,
      hasOpenrouterKey: !!this.settings.openrouterApiKey,
      geminiKeyHint: this.maskKey(this.settings.geminiApiKey),
      anthropicKeyHint: this.maskKey(this.settings.anthropicApiKey),
      elevenLabsKeyHint: this.maskKey(this.settings.elevenLabsApiKey),
      firecrawlKeyHint: this.maskKey(this.settings.firecrawlApiKey),
      perplexityKeyHint: this.maskKey(this.settings.perplexityApiKey),
      openaiKeyHint: this.maskKey(this.settings.openaiApiKey),
      openrouterKeyHint: this.maskKey(this.settings.openrouterApiKey),
      preferredProvider: this.settings.preferredProvider,
      openrouterModel: this.settings.openrouterModel,
      agentVoicesEnabled: this.settings.agentVoicesEnabled,
      wakeWordEnabled: this.settings.wakeWordEnabled,
      notificationWhisperEnabled: this.settings.notificationWhisperEnabled,
      notificationAllowedApps: this.settings.notificationAllowedApps,
      clipboardIntelligenceEnabled: this.settings.clipboardIntelligenceEnabled,
      googleCalendarEnabled: this.settings.googleCalendarEnabled,
      gatewayEnabled: this.settings.gatewayEnabled,
      hasTelegramToken: !!this.settings.telegramBotToken,
      telegramOwnerId: this.settings.telegramOwnerId || '',
      hasDiscordToken: !!this.settings.discordBotToken,
      discordOwnerId: this.settings.discordOwnerId || '',
      worldMonitorPath: this.settings.worldMonitorPath || '',
    };
  }

  async setAutoLaunch(enabled: boolean): Promise<void> {
    this.settings.autoLaunch = enabled;

    // Apply to Electron
    if (!app.isPackaged) {
      console.log('[Settings] Auto-launch skipped in dev mode');
    } else {
      app.setLoginItemSettings({
        openAtLogin: enabled,
        path: app.getPath('exe'),
      });
    }

    await this.save();
  }

  async setAutoScreenCapture(enabled: boolean): Promise<void> {
    this.settings.autoScreenCapture = enabled;
    await this.save();
  }

  async setObsidianVaultPath(vaultPath: string): Promise<void> {
    this.settings.obsidianVaultPath = vaultPath;
    await this.save();
  }

  getObsidianVaultPath(): string {
    return this.settings.obsidianVaultPath;
  }

  async setApiKey(key: 'gemini' | 'anthropic' | 'elevenlabs' | 'firecrawl' | 'perplexity' | 'openai' | 'openrouter', value: string): Promise<void> {
    if (key === 'gemini') {
      this.settings.geminiApiKey = value;
    } else if (key === 'anthropic') {
      this.settings.anthropicApiKey = value;
    } else if (key === 'elevenlabs') {
      this.settings.elevenLabsApiKey = value;
    } else if (key === 'firecrawl') {
      this.settings.firecrawlApiKey = value;
    } else if (key === 'perplexity') {
      this.settings.perplexityApiKey = value;
    } else if (key === 'openai') {
      this.settings.openaiApiKey = value;
    } else if (key === 'openrouter') {
      this.settings.openrouterApiKey = value;
    }

    this.applyApiKeys();
    await this.save();
  }

  async setSetting(key: string, value: unknown): Promise<void> {
    if (!(key in this.settings)) return;

    // Type-validate value against the expected type for this key
    const currentValue = (this.settings as unknown as Record<string, unknown>)[key];
    const expectedType = currentValue === null ? null : typeof currentValue;

    // Allow null for nullable fields (profiles, state objects)
    const nullableKeys = new Set([
      'intakeResponses', 'psychologicalProfile', 'featureSetupState', 'personalityEvolution', 'trustGraphConfig',
    ]);

    if (value === null && !nullableKeys.has(key)) {
      console.warn(`[Settings] Rejected null value for non-nullable key: ${key}`);
      return;
    }

    if (value !== null && expectedType !== null && typeof value !== expectedType) {
      // Allow arrays where arrays are expected
      if (Array.isArray(currentValue) && Array.isArray(value)) {
        // ok — both arrays
      } else if (typeof currentValue === 'object' && typeof value === 'object') {
        // ok — both objects (for complex types like FeatureSetupState)
      } else {
        console.warn(`[Settings] Type mismatch for "${key}": expected ${expectedType}, got ${typeof value}`);
        return;
      }
    }

    // Block direct modification of API keys through generic setSetting
    // (must use setApiKey() which has explicit key-name validation)
    const apiKeyFields = new Set([
      'geminiApiKey', 'anthropicApiKey', 'elevenLabsApiKey',
      'firecrawlApiKey', 'perplexityApiKey', 'openaiApiKey', 'openrouterApiKey',
    ]);
    if (apiKeyFields.has(key)) {
      console.warn(`[Settings] API key "${key}" must be set via setApiKey(), not setSetting()`);
      return;
    }

    (this.settings as unknown as Record<string, unknown>)[key] = value;
    await this.save();
  }

  /** Save the full agent identity config (called at end of onboarding) */
  async saveAgentConfig(config: AgentConfig): Promise<void> {
    this.settings.agentName = config.agentName;
    this.settings.agentVoice = config.agentVoice;
    this.settings.agentGender = config.agentGender;
    this.settings.agentAccent = config.agentAccent;
    this.settings.agentBackstory = config.agentBackstory;
    this.settings.agentTraits = config.agentTraits;
    this.settings.agentIdentityLine = config.agentIdentityLine;
    this.settings.userName = config.userName;
    this.settings.onboardingComplete = config.onboardingComplete;
    await this.save();

    // Sign identity after legitimate change (integrity protection)
    try {
      const { integrityManager } = require('./integrity');
      const identityJson = JSON.stringify(config, Object.keys(config).sort());
      await integrityManager.signIdentity(identityJson);
    } catch {
      // Integrity system may not be initialized yet during onboarding
    }

    console.log(`[Settings] Agent config saved: ${config.agentName} for ${config.userName}`);
  }

  /** Get just the agent identity configuration */
  getAgentConfig(): AgentConfig {
    return {
      agentName: this.settings.agentName,
      agentVoice: this.settings.agentVoice,
      agentGender: this.settings.agentGender,
      agentAccent: this.settings.agentAccent,
      agentBackstory: this.settings.agentBackstory,
      agentTraits: this.settings.agentTraits,
      agentIdentityLine: this.settings.agentIdentityLine,
      userName: this.settings.userName,
      onboardingComplete: this.settings.onboardingComplete,
    };
  }

  getGeminiApiKey(): string {
    return this.settings.geminiApiKey;
  }

  getAnthropicApiKey(): string {
    return this.settings.anthropicApiKey;
  }

  getElevenLabsApiKey(): string {
    return this.settings.elevenLabsApiKey;
  }

  getFirecrawlApiKey(): string {
    return this.settings.firecrawlApiKey;
  }

  getPerplexityApiKey(): string {
    return this.settings.perplexityApiKey;
  }

  getOpenaiApiKey(): string {
    return this.settings.openaiApiKey;
  }

  getOpenrouterApiKey(): string {
    return this.settings.openrouterApiKey;
  }

  getPreferredProvider(): 'anthropic' | 'openrouter' {
    return this.settings.preferredProvider || 'anthropic';
  }

  getOpenrouterModel(): string {
    return this.settings.openrouterModel || 'anthropic/claude-sonnet-4';
  }

  getWorldMonitorPath(): string {
    return this.settings.worldMonitorPath;
  }

  async setWorldMonitorPath(wmPath: string): Promise<void> {
    this.settings.worldMonitorPath = wmPath;
    await this.save();
  }

  isAgentVoicesEnabled(): boolean {
    return this.settings.agentVoicesEnabled && !!this.settings.elevenLabsApiKey;
  }

  private applyApiKeys(): void {
    if (this.settings.geminiApiKey) {
      process.env.GEMINI_API_KEY = this.settings.geminiApiKey;
    }
    if (this.settings.anthropicApiKey) {
      process.env.ANTHROPIC_API_KEY = this.settings.anthropicApiKey;
    }
    if (this.settings.elevenLabsApiKey) {
      process.env.ELEVENLABS_API_KEY = this.settings.elevenLabsApiKey;
    }
    if (this.settings.firecrawlApiKey) {
      process.env.FIRECRAWL_API_KEY = this.settings.firecrawlApiKey;
    }
    if (this.settings.perplexityApiKey) {
      process.env.PERPLEXITY_API_KEY = this.settings.perplexityApiKey;
    }
    if (this.settings.openaiApiKey) {
      process.env.OPENAI_API_KEY = this.settings.openaiApiKey;
    }
    if (this.settings.openrouterApiKey) {
      process.env.OPENROUTER_API_KEY = this.settings.openrouterApiKey;
    }
  }

  private maskKey(key: string): string {
    if (!key) return '';
    if (key.length <= 8) return '••••••••';
    return key.slice(0, 4) + '••••' + key.slice(-4);
  }

  private async save(): Promise<void> {
    // Serialize writes to prevent concurrent file corruption
    this.savePromise = this.savePromise.then(async () => {
      await fsAsync.writeFile(this.filePath, JSON.stringify(this.settings, null, 2), 'utf-8');
    }).catch((err) => {
      console.error('[Settings] Save failed:', err);
    });
    return this.savePromise;
  }
}

export const settingsManager = new SettingsManager();
