/**
 * settings.ts — Persistent settings storage for Agent Friday.
 * Stores to {userData}/friday-settings.json.
 */

import { app } from 'electron';
import fsAsync from 'fs/promises';
import fs from 'fs';
import path from 'path';

/** Current schema version. Increment when FridaySettings shape changes between releases. */
const CURRENT_SCHEMA_VERSION = 1;

/* ── Psychological Profile (generated by Claude Sonnet from onboarding intake) ── */
export interface PsychologicalProfile {
  openness: number;           // 0-1: How freely they share personal info
  trustReadiness: number;     // 0-1: How quickly they trust an AI companion
  emotionalDepth: number;     // 0-1: Depth of emotional engagement
  humorAsArmor: boolean;      // Do they use humor to deflect?
  guardedness: number;        // 0-1: How guarded/defensive they are
  connectionStyle: 'warm' | 'intellectual' | 'playful' | 'reserved';
  needsFromAI: string;        // What they likely need from an AI companion
  approachStrategy: string;   // How the agent should approach this person
  motherRelationshipInsight: string;  // Key insight from the mother question
  rawAnalysis: string;        // Full analysis text from Claude
}

/* ── Feature Setup State (guided post-onboarding walkthrough) ── */
export type FeatureSetupStep =
  | 'obsidian'
  | 'browser'
  | 'calendar'
  | 'email'
  | 'screen-capture'
  | 'world-monitor'
  | 'intelligence'
  | 'research'
  | 'ai-services'
  | 'voice'
  | 'gateway'
  | 'scheduler';

export interface FeatureSetupState {
  currentStep: number;
  steps: { id: FeatureSetupStep; status: 'pending' | 'completed' | 'skipped' }[];
}

/* ── Personality Evolution State (FridayCore visual uniqueness) ── */
export interface PersonalityEvolutionState {
  sessionCount: number;
  primaryHue: number;         // 0-360, derived from dominant trait
  secondaryHue: number;       // complementary hue
  particleSpeed: number;      // 0.5-2.0, maps to energy level
  cubeFragmentation: number;  // 0-1, maps to complexity/chaos
  coreScale: number;          // 0.8-1.5, maps to presence/confidence
  dustDensity: number;        // 0.5-2.0, maps to thoughtfulness
  glowIntensity: number;      // 0.5-2.0, maps to warmth
}

/* ── Trust Graph Configuration ── */
export interface TrustGraphConfig {
  maxPersons: number;            // Default 200
  evidenceRetention: number;     // Days to keep evidence, default 90
  decayRate: number;             // Trust decay per day of no interaction, default 0.001
  reEvalThreshold: number;       // Evidence count that triggers hermeneutic re-eval, default 5
}

/* ── Agent Trust State (user's trust in the agent — frustration detection & recovery) ── */
export interface AgentTrustState {
  score: number;              // 0-1, starts at 0.5
  frustrationSignals: number; // Count of detected frustration in current session
  corrections: number;        // Times user corrected the agent
  successStreak: number;      // Consecutive interactions without frustration signal
  lastFrustration: number;    // Timestamp of last detected frustration
  recoveryMode: boolean;      // True when trust is below 0.3
}

/* ── Intake Responses (raw answers from "Her" questions) ── */
export interface IntakeResponses {
  voicePreference: string;    // Male, female, or neither
  socialDescription: string;  // How they describe themselves socially
  motherRelationship: string; // The key question — or empty if deflected
}

export interface AgentConfig {
  agentName: string;
  agentVoice: string;          // 'Kore' | 'Puck' | 'Ember' | 'Breeze' | 'Juniper' | 'Orbiter'
  agentGender: string;         // 'female' | 'male' | 'neutral'
  agentAccent: string;         // e.g. 'British RP', 'American', 'Australian'
  agentBackstory: string;      // Freeform backstory paragraph
  agentTraits: string[];       // e.g. ['witty', 'warm', 'direct', 'playful']
  agentIdentityLine: string;   // What the agent says when asked who they are
  userName: string;            // The user's name
  onboardingComplete: boolean; // Whether full onboarding has been completed
}

export interface FridaySettings extends AgentConfig {
  /** Schema version for detecting settings shape changes across releases */
  schemaVersion: number;
  autoLaunch: boolean;
  autoScreenCapture: boolean;
  obsidianVaultPath: string;
  /** Additional directories to watch for file changes */
  fileWatchPaths: string[];
  geminiApiKey: string;
  anthropicApiKey: string;
  elevenLabsApiKey: string;
  firecrawlApiKey: string;
  perplexityApiKey: string;
  openaiApiKey: string;
  openrouterApiKey: string;
  /** Which model provider to prefer for agent tasks: 'anthropic' | 'openrouter' | 'local' | 'ollama' */
  preferredProvider: 'anthropic' | 'openrouter' | 'local' | 'ollama';
  /** OpenRouter model to use for agent tasks (e.g. 'anthropic/claude-sonnet-4') */
  openrouterModel: string;
  /** HuggingFace API token for cloud inference */
  huggingfaceApiKey: string;
  /** HuggingFace Inference API endpoint (default: HF cloud) */
  huggingfaceEndpoint: string;
  /** Local inference endpoint (TGI, vLLM, Ollama) */
  localInferenceEndpoint: string;
  /** Whether local model inference is enabled */
  localModelEnabled: boolean;
  /** Default model for local inference */
  localModelId: string;
  agentVoicesEnabled: boolean;
  wakeWordEnabled: boolean;
  notificationWhisperEnabled: boolean;
  notificationAllowedApps: string[];
  clipboardIntelligenceEnabled: boolean;
  googleCalendarEnabled: boolean;
  googleCalendarTokens: string;
  worldMonitorPath: string;
  // Gateway settings
  gatewayEnabled: boolean;
  telegramBotToken: string;
  telegramOwnerId: string;
  discordBotToken: string;
  discordOwnerId: string;
  // Onboarding & profile
  intakeResponses: IntakeResponses | null;
  psychologicalProfile: PsychologicalProfile | null;
  featureSetupComplete: boolean;
  featureSetupState: FeatureSetupState | null;
  personalityEvolution: PersonalityEvolutionState | null;
  // Desktop evolution (3D visualization structure index)
  desktopEvolutionIndex: number;
  desktopEvolutionLastChange: number;  // timestamp of last structure change
  // Trust Graph
  trustGraphConfig: TrustGraphConfig | null;
  // Agent Trust State (user's trust in the agent)
  agentTrustState: AgentTrustState | null;
  // Multimedia creation permissions
  creativePermissions: {
    canCreateOnRequest: true;
    canCreateDrafts: boolean;
    canCreateBriefings: boolean;
    canCreateUnprompted: boolean;
    canCreateAutonomously: boolean;
  } | null;
  // Onboarding checkpoint for crash recovery
  onboardingCheckpoint: {
    step: string;
    identityChoices?: { agentName: string; gender: string; voiceFeel: string };
  } | null;
  // Onboarding model & privacy selections
  /** Whisper STT model size selected during onboarding (e.g., 'tiny', 'base', 'small') */
  whisperModel: string;
  /** Embedding model selected during onboarding (e.g., 'nomic-embed-text') */
  embeddingModel: string;
  /** JSON-serialized personality slider values from manual calibration */
  personalitySliders: string;
  /** Memory depth: how aggressively the agent remembers context */
  memoryDepth: 'minimal' | 'standard' | 'comprehensive';
  /** Whether PII filtering is enabled */
  piiFiltering: boolean;
  /** Whether anonymous telemetry is enabled */
  telemetry: boolean;
  /** Whether to prefer local processing over cloud */
  localProcessing: boolean;
  /** Preferred voice engine: 'auto' probes in priority order */
  voiceEngine: 'auto' | 'personaplex' | 'local' | 'cloud';
  /** PersonaPlex HuggingFace token for model download */
  personaplexHfToken: string;
  /** PersonaPlex voice preset ID (e.g., 'NATF2') */
  personaplexVoiceId: string;
  /** Whether to offload PersonaPlex to CPU (slower but works without CUDA) */
  personaplexCpuOffload: boolean;
}

const DEFAULTS: FridaySettings = {
  schemaVersion: CURRENT_SCHEMA_VERSION,
  // Agent identity (configured during onboarding)
  agentName: '',
  agentVoice: 'Kore',
  agentGender: 'female',
  agentAccent: '',
  agentBackstory: '',
  agentTraits: [],
  agentIdentityLine: '',
  userName: '',
  onboardingComplete: false,
  // App settings
  autoLaunch: false,
  autoScreenCapture: true,
  obsidianVaultPath: '',
  fileWatchPaths: [],
  geminiApiKey: '',
  anthropicApiKey: '',
  elevenLabsApiKey: '',
  firecrawlApiKey: '',
  perplexityApiKey: '',
  openaiApiKey: '',
  openrouterApiKey: '',
  preferredProvider: 'anthropic',
  openrouterModel: 'anthropic/claude-sonnet-4',
  huggingfaceApiKey: '',
  huggingfaceEndpoint: 'https://api-inference.huggingface.co/v1',
  localInferenceEndpoint: 'http://localhost:11434/v1',
  localModelEnabled: false,
  localModelId: '',
  agentVoicesEnabled: true,
  wakeWordEnabled: true,
  notificationWhisperEnabled: true,
  notificationAllowedApps: ['Slack', 'Teams', 'Outlook', 'Calendar', 'Discord', 'WhatsApp', 'Telegram'],
  clipboardIntelligenceEnabled: true,
  googleCalendarEnabled: false,
  googleCalendarTokens: '',
  worldMonitorPath: '',
  // Gateway defaults
  gatewayEnabled: false,
  telegramBotToken: '',
  telegramOwnerId: '',
  discordBotToken: '',
  discordOwnerId: '',
  // Onboarding & profile defaults
  intakeResponses: null,
  psychologicalProfile: null,
  featureSetupComplete: false,
  featureSetupState: null,
  personalityEvolution: null,
  desktopEvolutionIndex: 0,
  desktopEvolutionLastChange: 0,
  trustGraphConfig: null,
  agentTrustState: null,
  creativePermissions: null,
  onboardingCheckpoint: null,
  whisperModel: '',
  embeddingModel: '',
  personalitySliders: '',
  memoryDepth: 'standard',
  piiFiltering: true,
  telemetry: false,
  localProcessing: true,
  voiceEngine: 'auto',
  personaplexHfToken: '',
  personaplexVoiceId: 'NATF2',
  personaplexCpuOffload: false,
};

class SettingsManager {
  private settings: FridaySettings = { ...DEFAULTS };
  private filePath = '';
  private savePromise: Promise<void> = Promise.resolve(); // Write queue to prevent concurrent file writes

  async initialize(): Promise<void> {
    const userDataDir = app.getPath('userData');

    // Migration: rename eve-settings.json → friday-settings.json
    const oldSettingsPath = path.join(userDataDir, 'eve-settings.json');
    const newSettingsPath = path.join(userDataDir, 'friday-settings.json');
    if (fs.existsSync(oldSettingsPath) && !fs.existsSync(newSettingsPath)) {
      fs.renameSync(oldSettingsPath, newSettingsPath);
    }

    // Migration: rename eve-data → friday-data
    const oldDataDir = path.join(userDataDir, 'eve-data');
    const newDataDir = path.join(userDataDir, 'friday-data');
    if (fs.existsSync(oldDataDir) && !fs.existsSync(newDataDir)) {
      fs.renameSync(oldDataDir, newDataDir);
    }

    // Migration: rename eve-intelligence.md → friday-intelligence.md
    const oldIntelPath = path.join(userDataDir, 'eve-intelligence.md');
    const newIntelPath = path.join(userDataDir, 'friday-intelligence.md');
    if (fs.existsSync(oldIntelPath) && !fs.existsSync(newIntelPath)) {
      fs.renameSync(oldIntelPath, newIntelPath);
    }

    this.filePath = path.join(userDataDir, 'friday-settings.json');

    try {
      // Vault-aware read: decrypts if vault is unlocked, falls back to plaintext
      const { vaultRead } = require('./vault');
      const data = await vaultRead(this.filePath);
      const saved = JSON.parse(data);
      this.settings = { ...DEFAULTS, ...saved };

      // Schema migration: detect and log version changes
      const savedVersion = saved.schemaVersion || 0;
      if (savedVersion < CURRENT_SCHEMA_VERSION) {
        console.log(`[Settings] Migrating settings from schema v${savedVersion} to v${CURRENT_SCHEMA_VERSION}`);
        this.settings.schemaVersion = CURRENT_SCHEMA_VERSION;
        // Future migrations go here (switch on savedVersion)
      }
    } catch {
      // First run — use defaults
    }

    // Merge in .env values if settings are empty (migration from .env-only setup)
    if (!this.settings.geminiApiKey && process.env.GEMINI_API_KEY) {
      this.settings.geminiApiKey = process.env.GEMINI_API_KEY;
    }
    if (!this.settings.anthropicApiKey && process.env.ANTHROPIC_API_KEY) {
      this.settings.anthropicApiKey = process.env.ANTHROPIC_API_KEY;
    }
    if (!this.settings.elevenLabsApiKey && process.env.ELEVENLABS_API_KEY) {
      this.settings.elevenLabsApiKey = process.env.ELEVENLABS_API_KEY;
    }
    if (!this.settings.firecrawlApiKey && process.env.FIRECRAWL_API_KEY) {
      this.settings.firecrawlApiKey = process.env.FIRECRAWL_API_KEY;
    }
    if (!this.settings.perplexityApiKey && process.env.PERPLEXITY_API_KEY) {
      this.settings.perplexityApiKey = process.env.PERPLEXITY_API_KEY;
    }
    if (!this.settings.openaiApiKey && process.env.OPENAI_API_KEY) {
      this.settings.openaiApiKey = process.env.OPENAI_API_KEY;
    }
    if (!this.settings.openrouterApiKey && process.env.OPENROUTER_API_KEY) {
      this.settings.openrouterApiKey = process.env.OPENROUTER_API_KEY;
    }
    if (!this.settings.huggingfaceApiKey && process.env.HF_TOKEN) {
      this.settings.huggingfaceApiKey = process.env.HF_TOKEN;
    }

    // Apply API keys to process.env so the rest of the app can use them
    this.applyApiKeys();

    console.log('[Settings] Initialized (autoLaunch:', this.settings.autoLaunch + ')');
  }

  /**
   * Re-read settings from disk after the vault is unlocked.
   *
   * During two-phase boot, settings are first loaded in Phase A (vault locked),
   * which means encrypted files fall back to defaults. This method is called
   * in Phase B (after vault unlock) to re-read the now-decryptable settings.
   *
   * Skips migration logic (already done in initialize()) — only re-reads + merges.
   */
  async reloadFromVault(): Promise<void> {
    if (!this.filePath) return; // Not initialized yet

    try {
      const { vaultRead } = require('./vault');
      const data = await vaultRead(this.filePath);
      const saved = JSON.parse(data);
      this.settings = { ...DEFAULTS, ...saved };
      this.applyApiKeys();
      console.log('[Settings] Reloaded from vault (post-unlock)');
    } catch {
      // File doesn't exist or is still plaintext defaults — keep current settings
      console.log('[Settings] No encrypted settings to reload (using current values)');
    }
  }

  get(): FridaySettings {
    return { ...this.settings };
  }

  /** Get settings with API keys masked for display */
  getMasked(): Record<string, unknown> {
    return {
      autoLaunch: this.settings.autoLaunch,
      autoScreenCapture: this.settings.autoScreenCapture,
      obsidianVaultPath: this.settings.obsidianVaultPath,
      hasGeminiKey: !!this.settings.geminiApiKey,
      hasAnthropicKey: !!this.settings.anthropicApiKey,
      hasElevenLabsKey: !!this.settings.elevenLabsApiKey,
      hasFirecrawlKey: !!this.settings.firecrawlApiKey,
      hasPerplexityKey: !!this.settings.perplexityApiKey,
      hasOpenaiKey: !!this.settings.openaiApiKey,
      hasOpenrouterKey: !!this.settings.openrouterApiKey,
      hasHuggingfaceKey: !!this.settings.huggingfaceApiKey,
      geminiKeyHint: this.maskKey(this.settings.geminiApiKey),
      anthropicKeyHint: this.maskKey(this.settings.anthropicApiKey),
      elevenLabsKeyHint: this.maskKey(this.settings.elevenLabsApiKey),
      firecrawlKeyHint: this.maskKey(this.settings.firecrawlApiKey),
      perplexityKeyHint: this.maskKey(this.settings.perplexityApiKey),
      openaiKeyHint: this.maskKey(this.settings.openaiApiKey),
      openrouterKeyHint: this.maskKey(this.settings.openrouterApiKey),
      huggingfaceKeyHint: this.maskKey(this.settings.huggingfaceApiKey),
      preferredProvider: this.settings.preferredProvider,
      openrouterModel: this.settings.openrouterModel,
      localModelEnabled: this.settings.localModelEnabled,
      localInferenceEndpoint: this.settings.localInferenceEndpoint,
      localModelId: this.settings.localModelId || '',
      agentVoicesEnabled: this.settings.agentVoicesEnabled,
      wakeWordEnabled: this.settings.wakeWordEnabled,
      notificationWhisperEnabled: this.settings.notificationWhisperEnabled,
      notificationAllowedApps: this.settings.notificationAllowedApps,
      clipboardIntelligenceEnabled: this.settings.clipboardIntelligenceEnabled,
      googleCalendarEnabled: this.settings.googleCalendarEnabled,
      gatewayEnabled: this.settings.gatewayEnabled,
      hasTelegramToken: !!this.settings.telegramBotToken,
      telegramOwnerId: this.settings.telegramOwnerId || '',
      hasDiscordToken: !!this.settings.discordBotToken,
      discordOwnerId: this.settings.discordOwnerId || '',
      worldMonitorPath: this.settings.worldMonitorPath || '',
      voiceEngine: this.settings.voiceEngine || 'auto',
      hasPersonaplexHfToken: !!this.settings.personaplexHfToken,
      personaplexHfTokenHint: this.maskKey(this.settings.personaplexHfToken),
      personaplexVoiceId: this.settings.personaplexVoiceId || 'NATF2',
      personaplexCpuOffload: this.settings.personaplexCpuOffload ?? false,
    };
  }

  async setAutoLaunch(enabled: boolean): Promise<void> {
    this.settings.autoLaunch = enabled;

    // Apply to Electron
    if (!app.isPackaged) {
      console.log('[Settings] Auto-launch skipped in dev mode');
    } else {
      app.setLoginItemSettings({
        openAtLogin: enabled,
        path: app.getPath('exe'),
      });
    }

    await this.save();
  }

  async setAutoScreenCapture(enabled: boolean): Promise<void> {
    this.settings.autoScreenCapture = enabled;
    await this.save();
  }

  async setObsidianVaultPath(vaultPath: string): Promise<void> {
    this.settings.obsidianVaultPath = vaultPath;
    await this.save();
  }

  getObsidianVaultPath(): string {
    return this.settings.obsidianVaultPath;
  }

  async setApiKey(key: 'gemini' | 'anthropic' | 'elevenlabs' | 'firecrawl' | 'perplexity' | 'openai' | 'openrouter' | 'huggingface', value: string): Promise<void> {
    // Serialize mutation + save to prevent interleaved modifications.
    // The in-memory write and applyApiKeys happen INSIDE the promise chain
    // so two concurrent setApiKey() calls cannot interleave assignments.
    let saveError: Error | undefined;
    this.savePromise = this.savePromise.then(async () => {
      if (key === 'gemini') {
        this.settings.geminiApiKey = value;
      } else if (key === 'anthropic') {
        this.settings.anthropicApiKey = value;
      } else if (key === 'elevenlabs') {
        this.settings.elevenLabsApiKey = value;
      } else if (key === 'firecrawl') {
        this.settings.firecrawlApiKey = value;
      } else if (key === 'perplexity') {
        this.settings.perplexityApiKey = value;
      } else if (key === 'openai') {
        this.settings.openaiApiKey = value;
      } else if (key === 'openrouter') {
        this.settings.openrouterApiKey = value;
      } else if (key === 'huggingface') {
        this.settings.huggingfaceApiKey = value;
      }

      this.applyApiKeys();
      const { vaultWrite } = require('./vault');
      await vaultWrite(this.filePath, JSON.stringify(this.settings, null, 2));
    }).catch((err) => {
      saveError = err instanceof Error ? err : new Error(String(err));
      console.error('[Settings] Save failed:', saveError.message);
    });
    await this.savePromise;
    if (saveError) {
      throw saveError;
    }
  }

  async setSetting(key: string, value: unknown): Promise<void> {
    if (!(key in this.settings)) return;

    // Type-validate value against the expected type for this key
    const currentValue = (this.settings as unknown as Record<string, unknown>)[key];
    const expectedType = currentValue === null ? null : typeof currentValue;

    // Allow null for nullable fields (profiles, state objects)
    const nullableKeys = new Set([
      'intakeResponses', 'psychologicalProfile', 'featureSetupState', 'personalityEvolution', 'trustGraphConfig',
      'onboardingCheckpoint',
    ]);

    if (value === null && !nullableKeys.has(key)) {
      console.warn(`[Settings] Rejected null value for non-nullable key: ${key}`);
      return;
    }

    if (value !== null && expectedType !== null && typeof value !== expectedType) {
      // Allow arrays where arrays are expected
      if (Array.isArray(currentValue) && Array.isArray(value)) {
        // ok — both arrays
      } else if (typeof currentValue === 'object' && typeof value === 'object') {
        // ok — both objects (for complex types like FeatureSetupState)
      } else {
        console.warn(`[Settings] Type mismatch for "${key}": expected ${expectedType}, got ${typeof value}`);
        return;
      }
    }

    // Crypto Sprint 6 (HIGH): Block direct modification of ALL sensitive credential fields
    // through the generic setSetting IPC. This is an allowlist-complement approach: we block
    // API keys, bot tokens, OAuth tokens, owner IDs, and gateway config. These fields must
    // only be set through dedicated, confirmation-gated APIs.
    const sensitiveFields = new Set([
      // API keys (must use setApiKey())
      'geminiApiKey', 'anthropicApiKey', 'elevenLabsApiKey',
      'firecrawlApiKey', 'perplexityApiKey', 'openaiApiKey', 'openrouterApiKey', 'huggingfaceApiKey',
      // Bot tokens and owner IDs — hijackable by compromised renderer
      'telegramBotToken', 'telegramOwnerId',
      'discordBotToken', 'discordOwnerId',
      // OAuth tokens
      'googleCalendarTokens',
      // Gateway control — enabling opens the app to inbound connections
      'gatewayEnabled',
    ]);
    if (sensitiveFields.has(key)) {
      console.warn(`[Settings] Sensitive field "${key}" cannot be set via setSetting()`);
      return;
    }

    // Serialize mutation + save to prevent interleaved modifications.
    // The in-memory write happens INSIDE the promise chain so two concurrent
    // setSetting() calls cannot interleave field assignments before the disk write.
    let saveError: Error | undefined;
    this.savePromise = this.savePromise.then(async () => {
      (this.settings as unknown as Record<string, unknown>)[key] = value;
      const { vaultWrite } = require('./vault');
      await vaultWrite(this.filePath, JSON.stringify(this.settings, null, 2));
    }).catch((err) => {
      saveError = err instanceof Error ? err : new Error(String(err));
      console.error('[Settings] Save failed:', saveError.message);
    });
    await this.savePromise;
    if (saveError) {
      throw saveError;
    }
  }

  /** Save the full agent identity config (called at end of onboarding) */
  async saveAgentConfig(config: AgentConfig): Promise<void> {
    // Serialize mutation + save to prevent interleaved modifications.
    // All field assignments happen INSIDE the promise chain atomically.
    let saveError: Error | undefined;
    this.savePromise = this.savePromise.then(async () => {
      this.settings.agentName = config.agentName;
      this.settings.agentVoice = config.agentVoice;
      this.settings.agentGender = config.agentGender;
      this.settings.agentAccent = config.agentAccent;
      this.settings.agentBackstory = config.agentBackstory;
      this.settings.agentTraits = config.agentTraits;
      this.settings.agentIdentityLine = config.agentIdentityLine;
      this.settings.userName = config.userName;
      this.settings.onboardingComplete = config.onboardingComplete;
      const { vaultWrite } = require('./vault');
      await vaultWrite(this.filePath, JSON.stringify(this.settings, null, 2));
    }).catch((err) => {
      saveError = err instanceof Error ? err : new Error(String(err));
      console.error('[Settings] Save failed:', saveError.message);
    });
    await this.savePromise;
    if (saveError) {
      throw saveError;
    }

    // Sign identity after legitimate change (integrity protection)
    try {
      const { integrityManager } = require('./integrity');
      const identityJson = JSON.stringify(config, Object.keys(config).sort());
      await integrityManager.signIdentity(identityJson);
    } catch {
      // Integrity system may not be initialized yet during onboarding
    }

    console.log(`[Settings] Agent config saved: ${config.agentName} for ${config.userName}`);
  }

  /** Get just the agent identity configuration */
  getAgentConfig(): AgentConfig {
    return {
      agentName: this.settings.agentName,
      agentVoice: this.settings.agentVoice,
      agentGender: this.settings.agentGender,
      agentAccent: this.settings.agentAccent,
      agentBackstory: this.settings.agentBackstory,
      agentTraits: this.settings.agentTraits,
      agentIdentityLine: this.settings.agentIdentityLine,
      userName: this.settings.userName,
      onboardingComplete: this.settings.onboardingComplete,
    };
  }

  getGeminiApiKey(): string {
    return this.settings.geminiApiKey;
  }

  getAnthropicApiKey(): string {
    return this.settings.anthropicApiKey;
  }

  getElevenLabsApiKey(): string {
    return this.settings.elevenLabsApiKey;
  }

  getFirecrawlApiKey(): string {
    return this.settings.firecrawlApiKey;
  }

  getPerplexityApiKey(): string {
    return this.settings.perplexityApiKey;
  }

  getOpenaiApiKey(): string {
    return this.settings.openaiApiKey;
  }

  getOpenrouterApiKey(): string {
    return this.settings.openrouterApiKey;
  }

  getHuggingfaceApiKey(): string {
    return this.settings.huggingfaceApiKey;
  }

  getPreferredProvider(): 'anthropic' | 'openrouter' | 'local' | 'ollama' {
    return this.settings.preferredProvider || 'anthropic';
  }

  getOpenrouterModel(): string {
    return this.settings.openrouterModel || 'anthropic/claude-sonnet-4';
  }

  getVoiceEngine(): string {
    return this.settings.voiceEngine || 'auto';
  }

  async setVoiceEngine(engine: string): Promise<void> {
    this.settings.voiceEngine = engine as FridaySettings['voiceEngine'];
    await this.save();
  }

  async setTelegramConfig(botToken: string, ownerId: string): Promise<void> {
    this.settings.telegramBotToken = botToken;
    this.settings.telegramOwnerId = ownerId;
    await this.save();
  }

  getPersonaplexHfToken(): string {
    return this.settings.personaplexHfToken || '';
  }

  async setPersonaplexHfToken(token: string): Promise<void> {
    this.settings.personaplexHfToken = token;
    await this.save();
  }

  getPersonaplexVoiceId(): string {
    return this.settings.personaplexVoiceId || 'NATF2';
  }

  async setPersonaplexVoiceId(id: string): Promise<void> {
    this.settings.personaplexVoiceId = id;
    await this.save();
  }

  getPersonaplexCpuOffload(): boolean {
    return this.settings.personaplexCpuOffload ?? false;
  }

  async setPersonaplexCpuOffload(v: boolean): Promise<void> {
    this.settings.personaplexCpuOffload = v;
    await this.save();
  }

  getWorldMonitorPath(): string {
    return this.settings.worldMonitorPath;
  }

  async setWorldMonitorPath(wmPath: string): Promise<void> {
    this.settings.worldMonitorPath = wmPath;
    await this.save();
  }

  isAgentVoicesEnabled(): boolean {
    return this.settings.agentVoicesEnabled && !!this.settings.elevenLabsApiKey;
  }

  /**
   * Previously applied API keys to process.env for legacy consumers.
   *
   * REMOVED (Crypto Sprint 5 — Fix H5): API keys in process.env are readable by
   * any code in the main process (MCP servers, connectors), visible in
   * /proc/PID/environ on Linux, and may appear in crash dumps.
   *
   * All consumers now use settingsManager getters:
   *   getAnthropicApiKey(), getGeminiApiKey(), getFirecrawlApiKey(), etc.
   *
   * This method is now a no-op retained for call-site compatibility.
   */
  private applyApiKeys(): void {
    // No-op: API keys are no longer written to process.env.
    // Use settingsManager.getXxxApiKey() instead.
  }

  /**
   * Remove API keys from process.env on shutdown.
   *
   * Now a no-op since applyApiKeys() no longer writes to process.env (Fix H5).
   * Retained for call-site compatibility. Still cleans up any keys that may
   * have been set by .env file loading at startup (dotenv, etc.).
   */
  clearApiKeysFromEnv(): void {
    const keysToRemove = [
      'GEMINI_API_KEY', 'ANTHROPIC_API_KEY', 'ELEVENLABS_API_KEY',
      'FIRECRAWL_API_KEY', 'PERPLEXITY_API_KEY', 'OPENAI_API_KEY',
      'OPENROUTER_API_KEY', 'HF_TOKEN',
    ];
    for (const key of keysToRemove) {
      delete process.env[key];
    }
  }

  /**
   * Reset all settings to factory defaults (Fix W7).
   * Erases psychological profile, agent config, API keys — everything.
   * The vault passphrase is NOT affected (that's vault.resetVaultFiles()).
   */
  async resetToDefaults(): Promise<void> {
    console.log('[Settings] Resetting all settings to defaults');
    this.settings = { ...DEFAULTS };
    await this.save();
  }

  private maskKey(key: string): string {
    if (!key) return '';
    if (key.length <= 8) return '••••••••';
    return key.slice(0, 4) + '••••' + key.slice(-4);
  }

  private async save(): Promise<void> {
    // Serialize writes to prevent concurrent file corruption.
    // Errors propagate to callers so they can handle save failures
    // (e.g. onboarding can show retry UI instead of silently advancing).
    //
    // IMPORTANT: We catch the error internally to keep the promise chain healthy
    // (otherwise one failed save would break ALL subsequent saves), but re-throw
    // it so the caller can handle it.
    let saveError: Error | undefined;
    this.savePromise = this.savePromise.then(async () => {
      // Vault-aware write: encrypts with AES-256-GCM (requires vault unlocked)
      const { vaultWrite } = require('./vault');
      await vaultWrite(this.filePath, JSON.stringify(this.settings, null, 2));
    }).catch((err) => {
      saveError = err instanceof Error ? err : new Error(String(err));
      console.error('[Settings] Save failed:', saveError.message);
      // Don't re-throw here — keep the promise chain alive for future saves
    });
    await this.savePromise;
    if (saveError) {
      throw saveError;
    }
  }
}

export const settingsManager = new SettingsManager();

// ── Sensitive environment variable list ────────────────────────────────
// Used to strip API keys from child process environments so spawned
// processes cannot inherit secrets from the parent Electron process.
const SENSITIVE_ENV_KEYS = [
  'GEMINI_API_KEY',
  'ANTHROPIC_API_KEY',
  'ELEVENLABS_API_KEY',
  'FIRECRAWL_API_KEY',
  'PERPLEXITY_API_KEY',
  'OPENAI_API_KEY',
  'OPENROUTER_API_KEY',
  'HF_TOKEN',
  // Common secret env vars that should never leak
  'AWS_SECRET_ACCESS_KEY',
  'AZURE_CLIENT_SECRET',
  'DATABASE_URL',
  'STRIPE_SECRET_KEY',
  'GITHUB_TOKEN',
  'SECRET_KEY',
  'PRIVATE_KEY',
];

/**
 * Returns a copy of process.env with all API keys and sensitive secrets removed.
 * Use this as the `env` option when spawning child processes to prevent
 * credential leakage to subprocesses.
 *
 * @example
 *   import { getSanitizedEnv } from './settings';
 *   spawn('node', ['script.js'], { env: getSanitizedEnv() });
 */
export function getSanitizedEnv(): Record<string, string | undefined> {
  const env = { ...process.env };
  for (const key of SENSITIVE_ENV_KEYS) {
    delete env[key];
  }
  // Also strip any key containing 'API_KEY' or 'SECRET' as a catch-all
  for (const key of Object.keys(env)) {
    if (/API_KEY|SECRET|_TOKEN$/i.test(key) && key !== 'SESSION_MANAGER') {
      delete env[key];
    }
  }
  return env;
}
