"""The installer's `$brainLadder` must never drift from `model_plan.BRAIN_MODELS`.

`packaging/windows/install.ps1` cannot import Python — the venv does not
exist yet at the point in the install where it asks "how should Friday
think" — so it carries its own copy of the brain ladder as a PowerShell
literal, generated by `scripts/gen_installer_ladder.py`. HR14
(`docs/design/implemented/headroom.md` §11): the installer's ladder is generated from
`model_plan.BRAIN_MODELS`; a test fails on drift. This is that test — it
parses the generated block out of `install.ps1` and diffs it against the
live `model_plan` module, rather than re-running the generator and diffing
files, so a hand-edit inside the markers is caught exactly as a hand-edit
that happened to leave the markers alone would be.

Companion to `test_wizard_bundled_model_drift.py`, which holds the same line
against `index.html`; both are Phase 0 fixes for defects named in
`headroom.md` §2.9.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
INSTALL_PS1 = REPO / "packaging" / "windows" / "install.ps1"

sys.path.insert(0, str(REPO / "src"))

from agent_friday.services import model_plan  # noqa: E402

_LADDER_BLOCK_RE = re.compile(
    r"# BEGIN GENERATED: brainLadder\r?\n"
    r"\$brainLadder = @\(\r?\n(?P<rows>.*?)\r?\n\)\r?\n"
    r"# END GENERATED: brainLadder",
    re.DOTALL,
)
_ROW_RE = re.compile(
    r"@\{\s*Id\s*=\s*'(?P<id>[^']+)'\s*;\s*"
    r"Needs\s*=\s*(?P<needs>[0-9.]+)\s*;\s*"
    r"Gb\s*=\s*(?P<gb>[0-9.]+)\s*;\s*"
    r"Says\s*=\s*'(?P<says>[^']*)'\s*\}"
)
_COMFORTABLE_RE = re.compile(
    r"# BEGIN GENERATED: localIsComfortable\r?\n"
    r"\$localIsComfortable = \(\$null -ne \$brainPick -and "
    r"\$brainPick\.Id -ne '(?P<id>[^']+)'\)\r?\n"
    r"# END GENERATED: localIsComfortable",
)


def _parsed_ladder():
    text = INSTALL_PS1.read_text(encoding="utf-8")
    m = _LADDER_BLOCK_RE.search(text)
    assert m, ("could not find the '# BEGIN/END GENERATED: brainLadder' "
               f"markers in {INSTALL_PS1}")
    rows = _ROW_RE.findall(m.group("rows"))
    assert rows, "brainLadder block matched but no rungs parsed out of it"
    return [
        {"id": rid, "needs": float(needs), "gb": float(gb), "says": says}
        for rid, needs, gb, says in rows
    ], text


def _pickable_brain_models():
    """The subset the installer should offer — mirrors
    `model_plan._pickable()`: only models that can call tools. A model the
    planner will never SELECT (`gemma3:4b`) must not be offered as a real
    rung either."""
    return [m for m in model_plan.BRAIN_MODELS if m["tools"]]


def test_installer_ladder_ids_and_order_match_model_plan():
    parsed, _ = _parsed_ladder()
    expected_ids = [m["id"] for m in _pickable_brain_models()]
    assert [row["id"] for row in parsed] == expected_ids, (
        "install.ps1's $brainLadder has drifted from model_plan.BRAIN_MODELS "
        "— run `python scripts/gen_installer_ladder.py`"
    )


def test_installer_ladder_figures_match_model_plan():
    parsed, _ = _parsed_ladder()
    by_id = {m["id"]: m for m in _pickable_brain_models()}
    for row in parsed:
        model = by_id[row["id"]]
        assert row["needs"] == model["vram_gib"], (
            f"{row['id']}: installer Needs={row['needs']} but "
            f"model_plan.vram_gib={model['vram_gib']} — regenerate the ladder"
        )
        assert row["gb"] == model["gib"], (
            f"{row['id']}: installer Gb={row['gb']} but "
            f"model_plan.gib={model['gib']} — regenerate the ladder"
        )


def test_installer_ladder_never_offers_a_tool_incapable_model():
    """The standing example: `gemma3:4b` is in BRAIN_MODELS so the planner
    can RECOGNISE it when installed, but `_pickable()` will never select it.
    The installer must not offer it as a download either."""
    parsed, _ = _parsed_ladder()
    tool_incapable = {m["id"] for m in model_plan.BRAIN_MODELS if not m["tools"]}
    offered = {row["id"] for row in parsed}
    assert not (offered & tool_incapable), (
        f"installer offers tool-incapable model(s): {offered & tool_incapable}"
    )


def test_local_is_comfortable_compares_against_floor_model():
    _, text = _parsed_ladder()
    m = _COMFORTABLE_RE.search(text)
    assert m, ("could not find the '# BEGIN/END GENERATED: localIsComfortable' "
               f"markers in {INSTALL_PS1}")
    assert m.group("id") == model_plan.FLOOR_MODEL, (
        f"$localIsComfortable compares against {m.group('id')!r} but "
        f"model_plan.FLOOR_MODEL is {model_plan.FLOOR_MODEL!r} — the literal "
        "qwen3:4b defect (KNOWN_ISSUES §1) this guards against"
    )
