"""A spoken yes with a condition attached never approves a card.

"Yes, but take out the part about my sister" is not consent to the card as
shown. It is consent to a card that does not exist yet. Typed chat refuses
those words — a card there is decided by its own buttons, so the sentence
revises the draft and asks again. Voice matched `yes` anywhere in the breath
and sent the unedited text.

So the condition now turns an approval into a revision: the instruction is
applied on this machine, the card comes back as a new version, and Friday
reads back what changed before asking again.

What she reads back is generated by the cloud voice model, so it is held to
the same rule as everything else on that side of the seam: it may repeat the
owner's own words, which the model already heard him say, and it may say how
much changed. It may not carry any of the draft's private text back out.
"""
import pytest

lc = pytest.importorskip("agent_friday.services.local_context")
ve = pytest.importorskip("agent_friday.services.voice_engine")

#: Private detail seeded into the draft. The model must never be handed this.
SISTER = "Her sister's custody hearing is on the 14th."
DRAFT = ("She is free on Saturday afternoon. " + SISTER
         + " She likes hiking on weekends.")

CONDITIONAL = [
    "yes, but take out the part about my sister",
    "yes, but leave out the part about my sister",
    "send it, but leave out the part about my sister",
    "go ahead, but drop the part about my sister",
]
PLAIN_YES = ["yes", "send it", "go ahead", "yep", "share it"]
PLAIN_NO = ["no", "don't send it", "decline", "cancel"]


def _card(text=DRAFT):
    """A pending share card, with its local seat and destination filled in."""
    out = lc.offer(text, conversation_id="conv-cond", cloud_model="smoke-cloud",
                   local_model="smoke-local", question="when is she free?")
    assert out.get("status") == "pending", out
    return out["approval_id"]


def _status(aid):
    from agent_friday.services import approvals
    return (approvals.get_approval(aid) or {}).get("status")


def _payload(aid):
    from agent_friday.services import approvals
    return (approvals.get_approval(aid) or {}).get("payload") or {}


# ── The words themselves ───────────────────────────────────────────────────

@pytest.mark.parametrize("words", CONDITIONAL)
def test_a_conditional_yes_is_not_an_approval(words):
    assert lc.spoken_decision(words, False) != "approve", (
        "a yes with a condition attached is consent to a card that does not "
        "exist yet")


@pytest.mark.parametrize("words", CONDITIONAL)
def test_a_conditional_yes_asks_for_a_revision(words):
    assert lc.spoken_decision(words, False) == "revise"


@pytest.mark.parametrize("words", PLAIN_YES)
def test_a_plain_yes_still_approves(words):
    assert lc.spoken_decision(words, False) == "approve"


@pytest.mark.parametrize("words", PLAIN_NO)
def test_a_plain_no_still_denies(words):
    assert lc.spoken_decision(words, False) == "deny"


def test_no_still_wins_over_yes_in_one_breath():
    assert lc.spoken_decision("yes - no, don't send it", False) == "deny"


def test_a_room_still_needs_friday_named():
    assert lc.spoken_decision("yes, but take out the part about my sister",
                              True) is None


def test_a_named_conditional_yes_in_a_room_still_revises():
    assert lc.spoken_decision(
        "Friday, yes, but take out the part about my sister", True) == "revise"


# ── The card does not move ─────────────────────────────────────────────────

@pytest.mark.parametrize("words", CONDITIONAL)
def test_a_conditional_yes_leaves_the_card_pending(words):
    aid = _card()
    res = lc.decide_by_voice(aid, words, False, "approve")
    assert not res.get("ok"), "a conditional yes must not decide the card"
    assert res.get("revise"), "it must be reported as a revision, not a refusal"
    assert _status(aid) == "pending", "the card must still be his to decide"


def test_a_plain_yes_still_decides_the_card():
    aid = _card()
    res = lc.decide_by_voice(aid, "send it", False, "approve")
    assert res.get("ok"), res
    assert _status(aid) == "approved"


# ── End to end through the voice tool ──────────────────────────────────────

def test_the_voice_tool_revises_and_asks_again():
    aid = _card()
    out = ve._tool_answer_share_request(
        {"request_id": aid, "decision": "approve"},
        session={"owner_text": "yes, but take out the part about my sister"})
    low = out.lower()
    assert "they approved" not in low and "he approved" not in low and not low.startswith("recorded:"), (
        "the model must not be told he approved it: " + out)
    assert _status(aid) == "pending"
    p = _payload(aid)
    assert int(p.get("version") or 1) >= 2, "the revision should be a new version"
    assert "sister" not in (p.get("text") or "").lower(), (
        "the condition should have been applied to the draft")
    assert "hiking" in (p.get("text") or ""), "the rest of the draft stays"


def test_the_read_back_carries_no_private_text_to_the_cloud_model():
    aid = _card()
    out = ve._tool_answer_share_request(
        {"request_id": aid, "decision": "approve"},
        session={"owner_text": "yes, but take out the part about my sister"})
    assert "custody hearing" not in out, (
        "the removed line must not travel to the cloud model in the read-back")
    assert "14th" not in out
    assert "Saturday" not in out, (
        "nor should the rest of the unapproved draft")


def test_the_model_is_told_to_read_back_and_ask_again():
    aid = _card()
    out = ve._tool_answer_share_request(
        {"request_id": aid, "decision": "approve"},
        session={"owner_text": "yes, but take out the part about my sister"})
    low = out.lower()
    assert "changed" in low or "took out" in low or "removed" in low, (
        "Friday has to say what changed: " + out)
    assert "send it" in low or "ask" in low, (
        "and ask him again: " + out)


def test_a_condition_that_cannot_be_applied_does_not_approve_either():
    """He named something the draft does not mention. Still not an approval."""
    aid = _card()
    out = ve._tool_answer_share_request(
        {"request_id": aid, "decision": "approve"},
        session={"owner_text": "yes, but take out the part about the mortgage"})
    assert "he approved" not in out.lower(), out
    assert _status(aid) == "pending", "nothing was sent and nothing was decided"


def test_a_plain_yes_through_the_tool_still_sends():
    aid = _card()
    out = ve._tool_answer_share_request(
        {"request_id": aid, "decision": "approve"},
        session={"owner_text": "send it"})
    assert "they approved" in out.lower(), out
    assert _status(aid) == "approved"
